### ISSUE TITLE
New configuration file wizard should show default values

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#100]
You know, users are lazy or overwhelmed, so show the default values.

---------------------------------------
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/100
- Originally Reported By: [Andreas Stührk](http://bitbucket.org/Trundle)
- Originally Created At: 2010-02-08T00:07:07.491

**Comment by Trundle** [comment]
I have not the slightest idea what I was trying to say with this issue. I assume it can be closed.
