### ISSUE TITLE
Can't run `bpython`: AttributeError: module 'xdg' has no attribute '__version__'

### ISSUE THREAD

**Issue by lulunac27a** [bpython/bpython#1001]
When I run the `bpython` command, I get an error message saying `AttributeError: module 'xdg' has no attribute '__version__'`. Even when I uninstall and install `bpython` again, it still gets the same error, and also gets the same error when I upgrade `xdg` and `pyxdg` to the latest version. 
```
Traceback (most recent call last):
  File "/Users/lulunac/opt/anaconda3/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/Users/lulunac/opt/anaconda3/lib/python3.9/site-packages/bpython/curtsies.py", line 204, in main
    config, options, exec_args = bpargs.parse(
  File "/Users/lulunac/opt/anaconda3/lib/python3.9/site-packages/bpython/args.py", line 215, in parse
    logger.info("pyxdg: %s", xdg.__version__)  # type: ignore
AttributeError: module 'xdg' has no attribute '__version__'
```

**Comment by sebastinas** [comment]
Which version of `pyxdg` do you have installed?

**Comment by lulunac27a** [comment]
I'm using the latest version of `pyxdg`: 0.28

**Comment by sebastinas** [comment]
Do the anaconda packages remove `pyxdg`'s `__version__`?

**Comment by lulunac27a** [comment]
Both `pyxdg` and `xdg` doesn't have a `__version__` attribute.

**Comment by sebastinas** [comment]
It does, though: https://github.com/takluyver/pyxdg/blob/master/xdg/__init__.py#L3
