### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableSet' For python3.10, python3.11

### ISSUE THREAD

**Issue by fire17** [bpython/bpython#1008]
Hi guys!
I just found out about bpython, looks amazing

Only i had trouble, i dont know why or where i saw to install from apt isntead of pip
Then relalized i cant use my own python3.11, it used py3.8

so i removed it, and reinstalled with `python3.11 -m pip install bpython`
but running it game this error
```
➜  xxx@xxx  ✗ bpython                                     12:40:19
Traceback (most recent call last):
  File "/home/magic/.local/bin//bpython", line 5, in <module>
    from bpython.curtsies import main
  File "/home/magic/.local/lib/python3.11/site-packages/bpython/curtsies.py", line 20, in <module>
    from .curtsiesfrontend.repl import BaseRepl
  File "/home/magic/.local/lib/python3.11/site-packages/bpython/curtsiesfrontend/repl.py", line 52, in <module>
    from .filewatch import ModuleChangedEventHandler
  File "/home/magic/.local/lib/python3.11/site-packages/bpython/curtsiesfrontend/filewatch.py", line 8, in <module>
    from watchdog.observers import Observer
  File "/usr/lib/python3/dist-packages/watchdog/observers/__init__.py", line 63, in <module>
    from .inotify import InotifyObserver as Observer
  File "/usr/lib/python3/dist-packages/watchdog/observers/inotify.py", line 76, in <module>
    from watchdog.observers.api import (
  File "/usr/lib/python3/dist-packages/watchdog/observers/api.py", line 23, in <module>
    from watchdog.utils.bricks import SkipRepeatsQueue
  File "/usr/lib/python3/dist-packages/watchdog/utils/bricks.py", line 175, in <module>
    class OrderedSet(collections.MutableSet):
                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableSet'
```

Luckily i found: https://stackoverflow.com/questions/74006130/attributeerror-module-collections-has-no-attribute-mutableset
which suggested adding the following
```
import collections 
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 10:
    from collections.abc import MutableSet
    collections.MutableSet = collections.abc.MutableSet
else: 
    from collections import MutableSet
```
I've manuallt edited `/usr/lib/python3/dist-packages/watchdog/utils/bricks.py`
and added these lines, where the `import collections` already exists (at the top)

AND IT WORKED! Now working for both python3.10 and python3.11!!
I would submit a pr, but this error comes from the watchdog dependency, i'll go there and try to submit it :)

Wrote this incase anyone was looking for a solutions
Thanks a lot and all the best!

**EDIT: I just checked, and it seems like they've already solved this issue in watchdog,
So i guees you guys need to update your dependencies!**
would make bpython usable in python>=3.10
Cheers!

**Comment by sebastinas** [comment]
You appear to be mixing a system installed watchdog package from a Python 3.8 installation installed via `apt`, with pip-installed bpython for Python 3.11. That's not going to work and is also not supported in general.

**Comment by fire17** [comment]
Hey man whats the deal, it looks like you half read what I said

I'm not mixing anything
I'm using 3.11 packages, with bpython 3.11

(I said that initially I mistakenly installed with apt but I removed it)

So yeah, just update your watchdog, and you will immediately support py3.10+

**Comment by fire17** [comment]
## #NotComplete

**Comment by sebastinas** [comment]
Given that pip installs the latest available version if no version constraints are in place, I'm not sure what you are doing and the traceback from above is the one from mixing with the apt package.
