### ISSUE TITLE
Update Watchdog Dependency - Support Python3.11 and Python3.10

### ISSUE THREAD

**Issue by fire17** [bpython/bpython#1009]
Hi there! you guys need to update your `watchdog` dependency to support running python>=3.10

I've put more details in #1008 which fixes:
`AttributeError: module 'collections' has no attribute 'MutableSet'` For python3.10, python3.11

Thanks a lot and all the best!

**Comment by sebastinas** [comment]
As in #1008, mixing Python 3.8 system packages with Python 3.11 pip installed bpython is not supported.

**Comment by fire17** [comment]
Not mixing anything...
## Definitely not complete
