### ISSUE TITLE
Customising `build.sub_commands` directly from `distutils` has been deprecated and is about to be removed

### ISSUE THREAD

**Issue by abravalheri** [bpython/bpython#1014]
The following feature in setuptools has been deprecated for almost 2 years and is about to be removed:

https://github.com/pypa/setuptools/blob/1ed759173983656734c3606e9c97a348895e5e0c/setuptools/command/build.py#L13-L27

It might be a good idea to import `build` directly from setuptools for the following code:

https://github.com/bpython/bpython/blob/ca13bf5727d91d3208e84297c2829aa8474b4620/setup.py#L131-L139

(`build` is available directly from setuptools, starting on version v62.4.0)

**Comment by sebastinas** [comment]
Maybe they could stop changing everything all the time.

**Comment by abravalheri** [comment]
> Maybe they could stop changing everything all the time.

Another possibility is to cap the version of setuptools in `pyproject.toml`... This way the project will not be affected by changes in setuptools.
