### ISSUE TITLE
<F1> Show Help

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#104]
Sometimes, the documentation for an object is too long to fit in the pop-up, and one might like to see the documentation for an object in the pager. Perhaps `<F1>` could be used there?

Or perhaps, extend the functionality of the `Pager` key - if no pop-up is open, then show last source in the pager; if a pop-up is open (completion or help, sometimes completion gets long too), then open that instead in the pager.

Personally, I would vote for the first idea (F1 -> Help) over the second...

---------------------------------------
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/104
- Originally Reported By: [ ](http://bitbucket.org/wackywendell)
- Originally Created At: 2010-02-22T19:13:04.716

**Comment by thomasballinger** [comment]
Using help solves this
