### ISSUE TITLE
Backspace kills line

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#11]
I've tried using bpython inside a screen session running in a PuTTY terminal and for pressing backspace (^H) discards the entire line and shows a prompt for new one in this case. Using Ctrl-Backspace does work as Backspace is supposed to but is rather inconvenient.

Here is all the relevant information I could think of, please let me know if you need anything else:

```
% cat /etc/issue
Debian GNU/Linux 5.0 \n \l
% uname -a
Linux xxxxxx 2.6.29-vz #1 SMP Sat May 23 19:43:27 CEST 2009 x86_64 GNU/Linux
% echo $TERM
screen
% stty -a
speed 38400 baud; rows 79; columns 200; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O;
min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon -iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```

---
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/11
- Originally Reported By: [ ](http://bitbucket.org/VZ)
- Originally Created At: 2009-06-03T11:59:31.518

**Comment by rgammans** [comment]
This bug is over [here -  [bpython on terminology backspace doesn't work] ]( https://bugs.launchpad.net/enlightenment-svn/+bug/1371209) in  launch pad  .

In this case since I have terminilogy and gnome-terminal installed I could see the only difference was the ERASE character setting in stty.

I've hacked up a patch here which works for me. rgammans/bpython@c22faa223e4ac92d6732f6d8d04c1c1d1e2a5ade

**Comment by lawlietfans** [comment]
hi,all 
i got same problem.  Is there has a easy way to fix this problem?

![image](https://cloud.githubusercontent.com/assets/8612867/19618318/94454474-9879-11e6-99a7-4c8b5124759e.png)
nobody answer this question :(

```sh
fsj@ubuntu:~$ bpython  -V
bpython version 0.12 on top of Python 2.7.6
(C) 2008-2012 Bob Farrell, Andreas Stuehrk et al. See AUTHORS for detail.
fsj@ubuntu:~$ uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:18:00 UTC 2015 i686 i686 i686 GNU/Linux
```
