### ISSUE TITLE
Allowing to navigate through code by ctrl+arrows

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#201]
Normally, it's possible to navigate through text in terminal (and almost any place) by using ctrl+left/right arrow. In BPython that doesn't work. 

---
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/201
- Originally Reported By: [Thiago Moraes](http://bitbucket.org/thiagocmoraes)
- Originally Created At: 2011-10-04T23:24:04.533

**Comment by nmtitov** [comment]
Thank you very much for that fix!
