### ISSUE TITLE
patch inspect.getsource so that I can get the source of interactively defined functions

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#229]
It seems like bpython is already saving a history of everything I type (so that it can be printed on exit); it would be really nifty if 'inspect.getsource' could show me the source of a function so that I could save things out individually.

---------------------------------------
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/229
- Originally Reported By: [ ](http://bitbucket.org/glyph)
- Originally Created At: 2012-10-04T02:18:02.077

**Comment by thomasballinger** [comment]
Looks like ipython does this by compiling functions with unique filenames for each prompt.
