### ISSUE TITLE
'bpython.cli.FakeStdin' don't have fileno() method

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#232]
'bpython.cli.FakeStdin' should have fileno() method

---
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/232
- Originally Reported By: Anonymous
- Originally Created At: 2012-10-22T11:42:08.347

**Comment by RichardBronosky** [comment]
I ran into this also. http://stackoverflow.com/questions/29757251/get-the-path-of-the-current-tty-in-python/29757597#29757597 I'm using ioctl http://stackoverflow.com/questions/29614264/unable-to-fake-terminal-input-with-termios-tiocsti/29616465#29616465 to send commands to a alternate local tty to solve the 'live demo typing' problem. The project is at https://github.com/RichardBronosky/ttysend but the use of `fileno()` has not been committed yet.

**Comment by thomasballinger** [comment]
For a workaround, you might use `sys.__stdout__` which isn't faked.
