### ISSUE TITLE
No way to view full command history

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#245]
At present, there doesn't appear to be a way to view your command history beyond the output of the most recent command.

Would it be difficult to add a configuration option to display the entire command history in the pager?  Or perhaps that functionality could be bound to another key?

I would think that a lot of people could get some use out of this.

---
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/245
- Originally Reported By: [David Sanders](http://bitbucket.org/davesque)
- Originally Created At: 2013-06-07T23:42:11.425

**Comment by mariomelofilho** [comment]
On Linux, on shell prompt(outside bpython)

`cat ~/.pythonhist`

as a workaround
