### ISSUE TITLE
Issue with the display of the auto-completion list

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#254]
Normally, The users in East Asian will setting to `Unicode East Asian Ambiguous characters are wide`.

A example, Terminal on Mac OS X:
Terminal.app's Preferences menu > Settings > Advanced tab > Check the `Unicode East Asian Ambiguous characters are wide`

`Unicode East Asian Ambiguous characters are wide` means displayed a UEAA character consuming the area of ​​*2* characters. It's critical issue when writing letters in Japanese and other languages.

see also: http://www.unicode.org/reports/tr11/

So, A problem of bpython is using u'\u2500' character when displaying the auto-completion list, because u'\u2500' character is UEAA character.

It should use `-` (hyphen) or any non-UEAA characters instead of UEAA characters.

Thank you.

---------------------------------------
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/254
- Originally Reported By: [takanao ENDOH](http://bitbucket.org/MiCHiLU)
- Originally Created At: 2013-10-01T15:46:50.565

**Comment by sebastinas** [comment]
I'm not sure what we should do here. The characters we use are those designated for box drawing. Unless somebody feels very passionate about this issues and provides us with a way to reproduce the problem, I'm going to close this report for now.

**Comment by sebastinas** [comment]
hmm, the fix is easy. So let's do it.
