### ISSUE TITLE
Can't see GTK3 constructor options.

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#256]
Try this for example:

```
#!python

from gi.repository import Gtk
Gtk.MessageDialog(
```

Unlike other modules, you don't get any help in a popup, or source with an F2. It would be awesome if it could give you GTK documentation, or at least a link to the GTK documentation.

---------------------------------------
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/256
- Originally Reported By: [ ](http://bitbucket.org/LBryan)
- Originally Created At: 2013-12-09T03:04:50.746

**Comment by sebastinas** [comment]
Let's close this. I think there is nothing we can do here.
