### ISSUE TITLE
bpython-curtsies needs to work with encodings other than UTF-8

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#295]
This shouldn't be too bad, but might require changing the way curtsies works. Any advice for how to go about testing different encodings? (this is an option I should look for in my terminal emulator, right?)

---------------------------------------
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/295
- Originally Reported By: [ ](http://bitbucket.org/thomasballinger)
- Originally Created At: 2014-06-30T18:48:05.392

**Comment by akshatsaha** [comment]
hi i just upgraded my bpython to be able to use scroll feature of bpython-curtsies. Though the scroll works as expected, suggestion box is coming as below:
â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”â”‚ abs(   all(   and    any(   apply( as     assert                                                                                                          â”‚
â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
any suggestions to solve this?

**Comment by sebastinas** [comment]
@akshatsaha: What are the values of your TERM, LANG and LC_* environment variables?

**Comment by thomasballinger** [comment]
Hm, it occurs to me we could do a cursor position detection hack to detect the encoding in use if the environmental variables can't be trusted.

**Comment by akshatsaha** [comment]
@sebastinas i am not sure about how to figure these out. i am using Putty terminal on Windows... And bpython works just fine with it... I can see the issue only with curtsies...

**Comment by sebastinas** [comment]
Running `env` will list all these variables. Did you tell Putty to use UTF-8? See http://thegreyblog.blogspot.co.at/2009/08/configuring-putty-to-use-utf-8.html for details.

**Comment by sebastinas** [comment]
Fixed by a5e541b.
