### ISSUE TITLE
Out of date documentation for themes configuration

### ISSUE THREAD

**Issue by john2x** [bpython/bpython#312]
At the moment, the [docs for themes](http://docs.bpython-interpreter.org/themes.html) says:

> bpython uses .theme files placed in your ~/.bpython directory. You can set the theme in the color_scheme option in your ~/bpython/config` file

It should instead say

> bpython uses .theme files placed in your `$XDG_CONFIG_HOME/bpython` directory. You can set the theme in the color_scheme option in your `$XDG_CONFIG_HOME/bpython/config` file

I checked the source of the docs, and they are correct. I guess the latest version just hasn't been uploaded yet.

**Comment by thomasballinger** [comment]
@ikanobori This is basically dealt with now, right?
