### ISSUE TITLE
Other completion modes

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#336]
@jasonLaster wrote code for fuzzy matching and substring matching. It'd be cool to use this somehow. He implemented it with a config option where you chose which you wanted - I wonder if there's something even better. If not, it would be nice to add these back. (they were removed when I "refactored" completion).

**Comment by thomasballinger** [comment]
Completion modes are back, see #510

**Comment by jasonLaster** [comment]
This is a good day for poor typers and short term memory loss! 

Seriously, great to see productivity wins.
