### ISSUE TITLE
bpython could pprint by default

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#34]
It would be nice if bpython could pprint the output by default. In an interactive interpreter, pretty printing things is much better, than the default printing.

Of course, this could be configurable for people that don't like pretty things. :)

---
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/34
- Originally Reported By: [ ](http://bitbucket.org/nilton)
- Originally Created At: 2009-06-15T03:25:32.728

**Comment by vdboor** [comment]
Sadly I couldn't easily get this to work. I don't see why BPython can't offer a convienience setting for this, instead of having to work through Python Internals. IPython does offer it:

```
$ ipython help notebook | grep pprint -A1
--pprint
    Enable auto pretty printing of results.
--
--no-pprint
    Disable auto auto pretty printing of results.
```
