### ISSUE TITLE
Termial.app window resizing interferes with bpython rerendering 

### ISSUE THREAD

**Issue by mlauter** [bpython/bpython#376]
If you have a long line of text that has been been printed to the bpython screen, resizing the terminal window does crazy stuff to your history. Lines end up being entirely removed or in the wrong places, extra whitespace lines can be inserted. 

Here I have an error message with a long line in the traceback that has been wrapped when initially printed:
![screen shot 2014-09-04 at 11 44 14 am](https://cloud.githubusercontent.com/assets/6538625/4151966/a2d8e31e-344a-11e4-8152-9559ebed7250.png)

After a bunch of lateral resizing the message has tripled, there is extra whitespace, and individual lines are no longer correct:
![screen shot 2014-09-04 at 11 45 09 am](https://cloud.githubusercontent.com/assets/6538625/4151969/a67526f4-344a-11e4-9df2-5a1278f27763.png)

**Comment by thomasballinger** [comment]
I've done a lot more terminal resizing work recently (https://github.com/thomasballinger/rlundo) and don't think we should be doing anything different wrt terminal resizing in bpython/curtsies than we are now.
