### ISSUE TITLE
debugging from within bpython

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#422]
There should be a better debugging story for bpython-curtsies - I just told someone to use bpython to explore some code, then to quit bpython and use pudb because invoking pudb doesn't work well from bpython-curtsies. I wonder what it would take to change this.

**Comment by sebastinas** [comment]
`bpdb` now uses the curtsies frontend. Using it to for debugging is documented at http://docs.bpython-interpreter.org/bpdb.html.
