### ISSUE TITLE
Use unicode within bpython (including upgrade to curtsies 0.2.0)

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#425]
Bpython-curtsies should be a unicode sandwich where curtsies provides the exit slice. All strings in bpython should be unicode.

I think. Right now the unicode output branch just casts to unicode during rendering, but this probably isn't a great strategy. If there are any problems with using unicode in cli.py or urwid.py however, this could be fine.

**Comment by thomasballinger** [comment]
To do:
* enumerate all the ways that text gets into bpython
* add tests that they're always unicode
* fix them

**Comment by keyanp** [comment]
I'm going to work on this issue this week.

**Comment by thomasballinger** [comment]
Cool, feel free to check in about it. I think "from __future__ import unicode_literals" should appear in more of our files, but it's hard to say across the board that they should be. One way to test this for completion would be to add that at the top of the file - there'd be a bunch of breaking tests immediately I think.

**Comment by thomasballinger** [comment]
Whoops, I guess there wouldn't be - `blue('a') == blue(u'a')` is True. But you could swap out the curtsies version and watch things call apart.

**Comment by thomasballinger** [comment]
We've put this off to beyond 0.14

**Comment by sebastinas** [comment]
Fixed in 1b6fba8640582dc43b59d015dcdde009e314c656.
