### ISSUE TITLE
Improve tests with unittest2

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#428]
Python 2.6 compatibility is a drag for using nice unittest.TestCase.assert* methods, and some of our tests are less readable (use assertTrue when they should use assertIn, assertTuple, etc) because of this. We should fix these tests and use unittest2 (a backport of new unitest features) for this.

**Comment by sebastinas** [comment]
I think this can be closed now. We're using unittest2 now for Python 2.6.
