### ISSUE TITLE
vim like key bindings

### ISSUE THREAD

**Issue by sanketsharma** [bpython/bpython#429]
Does bpython shell has vim like key bindings? I tried looking for it but couldn't find any.

**Comment by thomasballinger** [comment]
Closed as not happening anytime soon - but @sanketsharma you might check out Ctrl-x and F7 in bpython-curtsies, the first lets you edit the current line in your editor and the second lets you edit the entire session in your editor, then reruns it.

**Comment by mrestof-vre** [comment]
Sorry for necroposting, but is there any changes to this issue?
Also, @Julian, or anyone in the subject, do you know of any similar projects like PyVi, that allow you integrating vim parts in python apps?
Thanks for your time in advance.

**Comment by Julian** [comment]
(Blast from the past...).

No that day has still not come, and I'm not really aware of anything else which does this in general even at this point.
