### ISSUE TITLE
watchdog message should disappear after some time

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#437]
The message `Auto-reloading active, watching for file changes...` should disappear after some time.

**Comment by thomasballinger** [comment]
Hm, even if it's still watching? That's reasonable I guess, it's ugly to have it down there, and there'll be a message when it reloads

**Comment by sebastinas** [comment]
Yes. At least it's misplaced. Maybe we can find another location for it? Or we could hide it after some time but change ps1 to identicate that the whatchdog is active.
