### ISSUE TITLE
print startup file errors

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#438]
PYTHONSTARTUP environmental variable being set causes bout him curtsies frontend to read and run commands in the file name specified by this variable. (https://docs.python.org/2/using/cmdline.html#envvar-PYTHONSTARTUP)

If the var is set but the specified file doesn't exist, Bpyhon crashes. Behavior should match normal Python interpreter instead.

**Comment by thomasballinger** [comment]
Reopening for reasons described here: https://github.com/bpython/bpython/commit/3a86eaee6f0375a301d79ba8dfdf98ee535a1450

Summary: startup file should be run on undo, and crashes in startup file or inability to read from startup file should be errors that are displayed instead of hidden or crashing bpython.

**Comment by sebastinas** [comment]
I've created a new issue for the undo part (#450).

**Comment by sebastinas** [comment]
@thomasballinger, what do you think of the code in fix-438 branch (cf5f8d72fc24fd81f9fcf42049d871020a90877d)?
