### ISSUE TITLE
Redo some string operations

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#439]
In bpython/curtsiesfrontend/replyplainter.py, some string operations could be simplified by using `ljust` or `format`.

In https://github.com/bpython/bpython/blob/566dfe5a5fab815fdd8d04d6d3d131333c2a5800/bpython/curtsiesfrontend/replpainter.py#L159 `line+' '*(width - len(line)))[:width])` can be replaced by `line.ljust(width)[:width]` (untested).

**Comment by sebastinas** [comment]
Blocked by https://github.com/thomasballinger/curtsies/issues/62.

**Comment by thomasballinger** [comment]
No longer blocked, Curtsies 0.1.17 adds `ljust` and `rjust` that work as described here. (but bpython not updated yet)
