### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#449]
There are 3 or 4 (a guess) slow tests that make running the tests locally a pain. I think they're in importcompletion, but reading about [nosetests options](http://nose.readthedocs.org/en/latest/man.html) would probably yield something for timing or identifying slow tests.

These tests should be identified and sped up.

**Comment by sebastinas** [comment]
Using `nose-timer` and running `nosetests --with-timer`:
```
bpython.test.test_crashers.UrwidCrashersTest.test_issue108: 2.5460s
bpython.test.test_crashers.UrwidCrashersTest.test_issue133: 2.1666s
bpython.test.test_crashers.CursesCrashersTest.test_issue133: 1.2918s
bpython.test.test_crashers.CursesCrashersTest.test_issue108: 1.2561s
```

The urwid crasher tests are allready marked as `speed='slow'` and can be skipped with `nosetests -A "speed != 'slow'"`. We can mark the curses crasher tests in the same way.

**Comment by thomasballinger** [comment]
Ah cool thanks should have read those commits
