### ISSUE TITLE
rerun PYTHONSTARTUPFILE on undo

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#450]
Continuning the undo part from #438 here.

**Comment by thomasballinger** [comment]
I was conflicted about how to do this: it could be similar to how we treat `python -i module.py`, where the file isn't rerun and instead use "weak rewind"
~~~.py
        self.weak_rewind = bool(locals_ or interp) # If creating a new interpreter on undo
                                                   # would be unsafe because initial
                                                   # state was passed in
~~~
and code would be run without fancy highlighting etc.
OR
we could actually rerun. But now I think the PYTHONSTARTUP file really is special - we should rerun it every time. This makes this pretty easy to implement based on the recently added `class RunStartupFileEvent`.
