### ISSUE TITLE
Python config IOError

### ISSUE THREAD

**Issue by jpoler** [bpython/bpython#456]
On Ubuntu 14.04, hitting f3 to edit the config file doesn't work.

I follow the prompt and say test to create a new config file, and then get this message:

error creating file: IOError(2, 'No such file or directory')

**Comment by sebastinas** [comment]
Did you `setup.py install` bpython or `pip install` it? If so, then I guess that's due to 9d8a6aaeb674fb213de596447d438851159f5294.
