### ISSUE TITLE
pastebin, rewind, other keys don't work in bpython-urwid

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#461]
found when I was making sure 70ec8e98512c1b46ed71b7a4b2e8 wasn't breaking anything, but it wasn't working before these changes either.

Pastebin, show source, pager, save, and rewind also aren't working for me

**Comment by sebastinas** [comment]
It's like that forever: #142.

**Comment by thomasballinger** [comment]
Whoops, closed.
