### ISSUE TITLE
Regression introduced by 648d0b200ae896c3384e576b6df8d2b00d622f21

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#472]
Enter `max('', *[], key=len)` and execute it. Now go back in the history (arrow up), change `*[]` to `'2'` and execute it again. Notice how it executes the correct code, but the line changes back to `max('', *[], key=len)`.

A git bisect say that the issue was introduced in 648d0b200ae896c3384e576b6df8d2b00d622f21.

**Comment by thomasballinger** [comment]
ugh that's kind of bad
