### ISSUE TITLE
Path mangling for hacky virtualenvironment support

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#474]
IPython [changes sys.path to make virtual environments kinda sorta work](https://github.com/ipython/ipython/blob/master/IPython/core/interactiveshell.py#L726). I wonder if we should do this?

**Comment by sebastinas** [comment]
I don't think we should implement something like this. Too much magic, hacky and deviates from the default behaviour.

**Comment by thomasballinger** [comment]
sys.path trickery seems like a bad idea
