### ISSUE TITLE
Switch bpython.embed to curtsies

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#484]
`bpython.embed` still points to `bpython.cli`. This should also reflect the new default.

**Comment by sebastinas** [comment]
Before doing that we need to make `bpython.curtsies.main` behave like `bpython.cli.main`. There are two issues:

 * the return code from the script or obtained from `SystemExit` is reraised and thus killing the process after the first execution.
 * the session is not returned.

**Comment by sebastinas** [comment]
The second point is not relevant for curtsies.

**Comment by MrYoda** [comment]
How can I get embed with cli, not curtsies?
In curtsies mode not working some keys: home, delete, end (got it on Ubuntu 14.04, 15.04)

**Comment by thomasballinger** [comment]
from bpython.cli import main as oldbpython
    oldbpython(locals_=locals())
