### ISSUE TITLE
Home and End keys not working

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#490]
>Also I should note that in the default curtsies frontend Home and End keys don't work in several different terminals (konsole, gnome-terminal, both use TERM=xterm) (C-a & C-e do)

**Comment by thomasballinger** [comment]
Curtsies needs to implement these. https://github.com/thomasballinger/curtsies/issues/71

**Comment by sebastinas** [comment]
FWIW, they work fine with TERM=screen-256color.

**Comment by thomasballinger** [comment]
Using gnome-terminal on ubuntu on virtualbox with osx and doing some key remapping in osx land, I get
~~~
'\x1bOH' is called Home
'\x1bOF' is called End
'\x1b[1;2D' is called shift-left
'\x1b[1;2C' is called shift-right
'\x1b[1;2A' is called shift-up
'\x1b[1;2B' is called shift-down
~~~
That's too many levels of indirection - would someone else please try the following? `$ python -m curtsies.events` then follow the prompts, and paste in what you get here?

**Comment by thomasballinger** [comment]
@amorozov if you have time sometime seeing what your setup gets for Home and End would be great

**Comment by sebastinas** [comment]
```
% python3 -m curtsies.events
press a bunch of keys (not at the same time, but you can hit them pretty quickly)
---
b'\x1b[1~'
<HOME>
---
b'\x1b[4~'
<END>
---
```

**Comment by thomasballinger** [comment]
This means they're being detected fine for @sebastinas, we need one where they aren't.

**Comment by amorozov** [comment]
for TERM=xterm and konsole (v.2.4.12) in a recently updated KDE4:

'\x1b[H'
unknown!!!
Unidentified character sequence!
type 'ok' to prove you're not pounding keys ok
Press the key that produced '\x1b[H' again please
Describe in English what key you pressed: Home
---
'\x1b[F'
unknown!!!
Unidentified character sequence!
type 'ok' to prove you're not pounding keys ok
Press the key that produced '\x1b[F' again please
Describe in English what key you pressed: End

These keys (`\x1b[H` and `\x1b[F`) are also used when I use a remote connection via SSH to this workstation from default terminal program (likely Gnome Terminal) from Ubuntu-14.10. in that case TERM=xterm.

Also I've noticed that `<Insert>` is reported incorrectly:

'\x1b[2~'
<PADENTER>

**Comment by thomasballinger** [comment]
Awesome, thanks @amorozov.I'll add this soon assuming it doesn't ruin something else.

**Comment by thomasballinger** [comment]
@amorozov I've release a new version of Curtsies with this - `pip install curtsies --upgrade` should hopefully fix this if you're using the latest bpython. (I can't test it though, so look forward to hearing if this fixes the problem).

**Comment by amorozov** [comment]
Thanks a lot!

I've just tested it in Konsole, and everything works fine. Since Konsole and Gnome Terminal use the same sequences I don't expect any problem in case "Remote Gnome Terminal from Ubuntu" as well

**Comment by amorozov** [comment]
Hmm, likely keys `<Insert>` and `<KP_Insert>` still generate `<PADENTER>` event.

I'm not sure it's rather important, since `<Insert>` is only useful in vi-like keybindings, but nevertheless...

**Comment by thomasballinger** [comment]
Ah I didn't fix insert, figured it was less urgent since it didn't do anything useful in bpython. I'll put that on the queue.

**Comment by RichardBronosky** [comment]
Upgrading to the latest curtsies worked on my Mac:

    mbp:~ bruno$ pip install curtsies --upgrade
    Collecting curtsies from https://pypi.python.org/packages/2.7/c/curtsies/curtsies-0.2.3-py2.py3-none-any.whl#md5=4f29e9d9472fb79968892168e526ee5d
      Using cached curtsies-0.2.3-py2.py3-none-any.whl
    Requirement already up-to-date: blessings>=1.5 in /usr/local/lib/python2.7/site-packages (from curtsies)
    Requirement already up-to-date: wcwidth>=0.1.4 in /usr/local/lib/python2.7/site-packages (from curtsies)
    Installing collected packages: curtsies
      Found existing installation: curtsies 0.1.18
        Uninstalling curtsies-0.1.18:
          Successfully uninstalled curtsies-0.1.18

    Successfully installed curtsies-0.2.3

    mbp:~ bruno$ python -m curtsies.events
    press a bunch of keys (not at the same time, but you can hit them pretty quickly)
    ---
    '\x1b[H'
    <HOME>
    ---
    '\x1b[F'
    <END>

Unfortunately, bpython didn't work with it:

    mbp:~ bruno$ bpython
    bpython version 0.14.1 on top of Python 2.7.9 /usr/local/opt/python/bin/python2.7

    Traceback (most recent call last):
      File "/usr/local/bin/bpython", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 79, in main
        interactive=(not exec_args))
      File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 163, in mainloop
        process_event(bpythonevents.RunStartupFileEvent())
      File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 145, in process_event
        array, cursor_pos = repl.paint()
      File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1134, in paint
        current_line = paint.paint_current_line(min_height, width, self.current_cursor_line)
      File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1083, in current_cursor_line
        return (self.current_cursor_line_without_suggestion +
      File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1076, in current_cursor_line_without_suggestion
        ('' if self.coderunner.running else self.display_line_with_prompt))
      File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1069, in display_line_with_prompt
        if self.done else
      File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 615, in fmtstr
        string = FmtStr.from_str(string)
      File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 169, in from_str
        return FmtStr(Chunk(s))
      File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 70, in __init__
        raise ValueError("unicode string required, got %r" % string)
    ValueError: unicode string required, got '>>> '

Then I tried to upgrade bpython and got:

    mbp:~ bruno$ pip install bpython --upgrade --no-cache-dir
    Requirement already up-to-date: bpython in /usr/local/lib/python2.7/site-packages
    Collecting curtsies<0.2.0,>=0.1.18 (from bpython)
      Downloading curtsies-0.1.18-py2.py3-none-any.whl
    Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/site-packages (from bpython)
    Requirement already up-to-date: pygments in /usr/local/lib/python2.7/site-packages (from bpython)
    Requirement already up-to-date: requests in /usr/local/lib/python2.7/site-packages (from bpython)
    Requirement already up-to-date: greenlet in /usr/local/lib/python2.7/site-packages (from bpython)
    Requirement already up-to-date: blessings>=1.5 in /usr/local/lib/python2.7/site-packages (from curtsies<0.2.0,>=0.1.18->bpython)
    Installing collected packages: curtsies
      Found existing installation: curtsies 0.2.3
        Uninstalling curtsies-0.2.3:
          Successfully uninstalled curtsies-0.2.3

    Successfully installed curtsies-0.1.18

And once again I have not Home or End keys.

**Comment by RichardBronosky** [comment]
Though it does works in the version 0.15.dev85

    git clone https://github.com/bpython/bpython.git
    pip install --upgrade ./bpython

**Comment by thomasballinger** [comment]
@RichardBronosky This is expected, bpython 0.14.x (the last released version) doesn't work with Curtsies >= 0.2.0. If you `pip uninstall curtsies` and `pip install bpython` you should have a working setup again, or you can use the latest development version as you're doing now in order to use the newest Curtsies version. I'll add these two keys in a bugfix to Curtsies 0.1.x today, so users of the released version of bpython can get this fix with

    $ pip uninstall curtsies
    $ pip install bpython

**Comment by thomasballinger** [comment]
@RichardBronosky This has been added in Curtsies v0.1.19, just released.

**Comment by ohnoleo** [comment]
Just a heads up, on my system I'm getting:

- \x1bOH for <HOME>
- \x1bOF for <END>

Running in under terminator 0.97 and bash 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by thomasballinger** [comment]
Sorry about that @ohnoleo. I'm hoping to change how keys are detected by using the curses wrapper https://github.com/jquast/blessed which will mean Curtsies doesn't have to maintain its own database. It looks like this is reported at https://github.com/thomasballinger/curtsies/issues/78, so if there's a little release before the big change I'll get it in that.

**Comment by ohnoleo** [comment]
No worries! It's easy to fix on my local installation.
Thanks for the great interpreter :)

**Comment by amorozov** [comment]
I'd like to ask if this means that wrong keys should be reported to `blessed` or to some other place? I still get `Home` and `End` unrecognized with the most recent curtsies from master (the keys are

     press a bunch of keys (not at the same time, but you can hit them pretty quickly)
     ---
     '\x1b[H'
     <HOME>
     ---
     '\x1b[F'
     <END>

TERM=xterm, konsole via ssh or locally. I know that the default terminal emulator in the most recent Ubuntu (gnome-terminal I think) gives the same keycodes.

**Comment by thomasballinger** [comment]
@amorozov Curtsies currently maintains it's own database. These keys are in Curtsies master at https://github.com/thomasballinger/curtsies/blob/master/curtsies/events.py#L64 but aren't in the version currently used by bpython. There will be a bpython release (0.15.0) soon that will update the Curtsies version, but unfortunately Curtsies 0.1.x used by bpython doesn't have these keys.

**Comment by amorozov** [comment]
Unfortunately I'm talking about curtsies from master, I've just updated it to be sure.

The codes for `xterm` in Konsole and Gnome-Terminal in Fedora and few other distros aren't equal to those in the file.

**Comment by thomasballinger** [comment]
Oh sorry I missed that - I've added them (https://github.com/thomasballinger/curtsies/commit/c9a88abb519023cd4ba9e878e5cb2d391f989174) and will do a release with the new bpython.

**Comment by AgustinLado** [comment]
Hello, just wanted to comment like ohnoleo said that I'm getting the codes `\x1bOH` for <HOME> and `\x1bOF` for <END>.
I'm running bpython version 0.15 on a Guake Terminal 0.8.4 with GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu).

I'm unsure what I should configure in my terminal for getting the (apparently more normal) `\x1b[H` and `\x1b[F`. When I run `echo $TERM` I get the output "xterm" but running `export TERM=xterm-256color` makes no difference.

**Comment by thomasballinger** [comment]
Thanks, sounds like I need to fix Curtsies with this. I hope to get to this soon, possibly right after PyCon.

**Comment by krigstask** [comment]
The same problem with *rxvt-unicode*.

`keylog.txt`:
```
'\x1b[7~' is called Home
'\x1b[8~' is called End
```
