### ISSUE TITLE
Initial input

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#492]
bpython is a little slower to start now (this should be a separate issue) but it makes an existing curtsies bug worse: typing a line of input and hitting enter before bpython is done initializing will lose that input. Reported by @julian.

**Comment by thomasballinger** [comment]
This is fixed by https://github.com/thomasballinger/curtsies/commit/8cf3ea80603dc90421ce5305f864df9bcf21573a which is in the newest curtsies release, 0.2.3.

**Comment by Julian** [comment]
:+1:
