### ISSUE TITLE
bpython is slow to start up

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#493]
bpython takes a long time to start up now. Reported by @jimjshields

There are probably some interesting things we could do to mitigate this, most involving giving the users a less fully functional version of bpython sooner. We already push off import completion to after the user can start interacting, maybe something else could also happen later: things like completion, dependencies for pastebin, jedi completion, etc could happen later as long as they don't cost a lot of code complexity.

**Comment by sebastinas** [comment]
Before doing anything here, we need to profile bpython first.

**Comment by thomasballinger** [comment]
Absolutely, no uglifying of the code allowed without evidence.

**Comment by thomasballinger** [comment]
To investigate this, I suggest modifying bpython/curtsies.py to immediately send a "<Ctrl-d>" event after the `process_event(None)` call on line ~175, and then running that script directly with a profiler of choice (`python -m cProfile -s cumtime script.py` would be an example, if you've made a copy of `bpython/curtsies.py` called `script.py`)

If you'd like help interpreting the results, let me know and we can look together.

**Comment by thomasballinger** [comment]
This is resolved, it was mostly importing requests and jedi.

**Comment by thomasballinger** [comment]
I use https://github.com/thomasballinger/lazyload to make imports of requests and jedi lazy by adding the line

    import lazyload; lazyload.make_lazy('requests'); lazyload.make_lazy('jedi')

to the installed executable bpython script, but I don't recommend this and it isn't supported.
