### ISSUE TITLE
bpython requires.txt not synchronized with latest version of curtsies

### ISSUE THREAD

**Issue by ztomer** [bpython/bpython#495]
After updating bpython to 0.14 with pip --upgrade (using python 3.4.3, osX 10.10.2, and homebrew) 

running bpython fails with the following message:

`pkg_resources.ContextualVersionConflict: (curtsies 0.2.3 (/usr/local/lib/python3.4/site-packages), Requirement.parse('curtsies<0.2.0,>=0.1.18'), {'bpython'})`

Can be fixed by modifying
`/usr/local/lib/python3.4/site-packages/bpython-0.14-py3.4.egg-info/requires.txt`

and changing the line
`curtsies >=0.1.18, <0.2.0`
to 
`curtsies >=0.1.18, <0.2.4`

**Comment by sebastinas** [comment]
The requirement is correct. bpython 0.14 does not work with curtsies 0.2.x (untested with Python 3.x, does not work at all with Python 2.x). To use curtsies 0.2.x, you need to use bpython's master branch.
