### ISSUE TITLE
The availability of remapping Esc-R (reverse-i-search) to Ctrl-R

### ISSUE THREAD

**Issue by karolyi** [bpython/bpython#499]
Hey guys,

I'm looking for the option to specify reverse-i-search to work with ctrl-r instead of esc-r, as my yosemite terminal sucks locally, and esc-r does not work. Also, I'm a libreadline junkie, and I'd like that reverse-i-search option to appear on ctrl-r.

Could you please provide a keyboard config option for this?

**Comment by thomasballinger** [comment]
Looks like it's not configurable yet:
~~~py
         elif e in ("<Esc+r>",):
             self.incremental_search(reverse=True)
         elif e in ("<Esc+s>",):
             self.incremental_search()
~~~
This should be fixed. I think it's not there because I was putting it off to see if we could agree to fix it for everyone - ie make the new defaults match readline - but I think that's unlikely at this point.

**Comment by thomasballinger** [comment]
https://github.com/bpython/bpython/compare/tmp  may fix things

**Comment by karolyi** [comment]
is this in production yet?

**Comment by karolyi** [comment]
I see it in master, but not in the 0.14 branch, which gets deployed with pip.

**Comment by thomasballinger** [comment]
@karolyi Yep, this won't be released as a bugfix, so we'll have to wait for the next release or use master.

**Comment by karolyi** [comment]
@thomasballinger thx. when do you anticipate it?
