### ISSUE TITLE
getpreferredencoding() returns empty string so test crashes on fresh checkout 

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#513]
https://gist.github.com/rhymeswithcycle/308fb69ae43cccd86fcb

This might not be our fault, but saving it here to look into it later

**Comment by sebastinas** [comment]
Any improvement with 21b9a54?

**Comment by rhymeswithcycle** [comment]
Yep -- that was my system on which the test initially failed, and with that commit the test now passes.
