### ISSUE TITLE
OSX 10.10 Yosemite Error -- GCC 4.2 Failed With Exit Status 1 When Compiling bpython

### ISSUE THREAD

**Issue by weems** [bpython/bpython#519]
Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/var/folders/bc/cmnr0l6n1vb76p28m_4vlwh00000gn/T/pip-build-9yEUoD/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/bc/cmnr0l6n1vb76p28m_4vlwh00000gn/T/pip-i2DjPf-record/install-record.txt --single-version-externally-managed --compile:
    running install

    running build

    running build_ext

    building 'greenlet' extension

    creating build

    creating build/temp.macosx-10.10-x86_64-2.7

    /usr/local/bin/gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c greenlet.c -o build/temp.macosx-10.10-x86_64-2.7/greenlet.o

    <built-in>:0: error: Unknown value ‘10.10’ of -mmacosx-version-min

    error: command '/usr/local/bin/gcc-4.2' failed with exit status 1

**Comment by sebastinas** [comment]
Not a bpython issue. Please report it to the greenlet developers.

**Comment by weems** [comment]
Attempted a clone of the github repo instead of installing from PyPi, and received the following Traceback:

Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 3018, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 614, in _build_master
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 627, in _build_from_requirements
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 805, in resolve
pkg_resources.DistributionNotFound: greenlet
