### ISSUE TITLE
Dependency pyasn1 not installed with bpython

### ISSUE THREAD

**Issue by thekthuser** [bpython/bpython#523]
(venv)user@kth: pip install -e .
    Obtaining file:///home/user/Work/bpython/bpython
      Running setup.py egg_info for package from file:///home/user/Work/bpython/bpython
	
	warning: no files found matching 'bpython/translations/*/LC_MESSAGES/bpython.mo'
    Requirement already satisfied (use --upgrade to upgrade): pygments in /home/user/Work/bpython/venv/lib/python2.7/site-packages (from bpython==0.15.dev105)
    Requirement already satisfied (use --upgrade to upgrade): requests in /home/user/Work/bpython/venv/lib/python2.7/site-packages (from bpython==0.15.dev105)
    Requirement already satisfied (use --upgrade to upgrade): curtsies>=0.1.18 in /home/user/Work/bpython/venv/lib/python2.7/site-packages (from bpython==0.15.dev105)
    Requirement already satisfied (use --upgrade to upgrade): greenlet in /home/user/Work/bpython/venv/lib/python2.7/site-packages (from bpython==0.15.dev105)
    Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /home/user/Work/bpython/venv/lib/python2.7/site-packages (from bpython==0.15.dev105)
    Requirement already satisfied (use --upgrade to upgrade): blessings>=1.5 in /home/user/Work/bpython/venv/lib/python2.7/site-packages (from curtsies>=0.1.18->bpython==0.15.dev105)
    Requirement already satisfied (use --upgrade to upgrade): wcwidth>=0.1.4 in /home/user/Work/bpython/venv/lib/python2.7/site-packages (from curtsies>=0.1.18->bpython==0.15.dev105)
    Installing collected packages: bpython
      Running setup.py develop for bpython
	
	warning: no files found matching 'bpython/translations/*/LC_MESSAGES/bpython.mo'
	Creating /home/user/Work/bpython/venv/lib/python2.7/site-packages/bpython.egg-link (link to .)
	bpython 0.15.dev105 is already the active version in easy-install.pth
	Installing bpython-urwid script to /home/user/Work/bpython/venv/bin
	Installing bpython-curses script to /home/user/Work/bpython/venv/bin
	Installing bpdb script to /home/user/Work/bpython/venv/bin
	Installing bpython script to /home/user/Work/bpython/venv/bin
	
	Installed /home/user/Work/bpython/bpython
    Successfully installed bpython
    Cleaning up...
    (venv)user@kth:~/Work/bpython/bpython> bpython
    Traceback (most recent call last):
      File "/home/user/Work/bpython/venv/bin/bpython", line 5, in <module>
	from pkg_resources import load_entry_point
      File "/home/user/Work/bpython/venv/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
	working_set.require(__requires__)
      File "/home/user/Work/bpython/venv/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
	needed = self.resolve(parse_requirements(requirements))
      File "/home/user/Work/bpython/venv/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
	raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: pyasn1
    (venv)user@kth:~/Work/bpython/bpython> python --version
    Python 2.7.6
    (venv)user@kth:~/Work/bpython/bpython> uname -a
    Linux kth.site 3.11.10-29-desktop #1 SMP PREEMPT Thu Mar 5 16:24:00 UTC 2015 (338c513) x86_64 x86_64 x86_64 GNU/Linux

**Comment by sebastinas** [comment]
Please install requests[security] as specified in setup.py.

**Comment by thomasballinger** [comment]
Is there anything we could do to get this installing by default if needed? Right now `pip install bpython` just fails for earlier versions of python.

**Comment by thomasballinger** [comment]
What's the preceding colon about? I"m trying to find docs on it now.

**Comment by thomasballinger** [comment]
After these changes the following works for me with a fresh Ubuntu 14.04 (which uses Python 2.7.6):
~~~
$ sudo apt-get update
$ sudo apt-get install python-pip python-greenlet git
$ git clone https://github.com/bpython/bpython.git
$ sudo pip install --upgrade pip
$ sudo pip install ./bpython
~~~
