### ISSUE TITLE
bpython draws across tmux borders

### ISSUE THREAD

**Issue by sigmavirus24** [bpython/bpython#535]
Steps to reproduce:

1. Open a tmux session
2. Make a vertical split
3. Start bpython in one of the vertical splits (it will draw across them either way, just in different ways, see the screenshots)
4. Start typing `im` and the completion box drawn below will span the entire terminal window instead of just the terminal in the split

Split set up:

![screen shot 2015-05-09 at 3 51 23 pm](https://cloud.githubusercontent.com/assets/240830/7552005/ad260e42-f663-11e4-96a6-36daf43cb11b.png)

Start bpython:

![screen shot 2015-05-09 at 3 51 37 pm](https://cloud.githubusercontent.com/assets/240830/7552006/b1c1c428-f663-11e4-815f-eba570be6eef.png)

Start typing `im`:

![screen shot 2015-05-09 at 3 51 54 pm](https://cloud.githubusercontent.com/assets/240830/7552007/bb03a902-f663-11e4-9731-9404f20a3024.png)

Results if bpython is on the right split:

![screen shot 2015-05-09 at 3 53 19 pm](https://cloud.githubusercontent.com/assets/240830/7552010/c37e3d9a-f663-11e4-96aa-d1d738cfcc75.png)

I haven't even begun to look into why this is the case, but it's a bit surprising. This could be a bug in the underlying curses libraries used by bpython.

Also

```
❯❯❯ pip freeze | ag bpython
bpython==0.14.1
```

**Comment by thomasballinger** [comment]
Wow, pretty weird! What version of tmux are you using? I can't reproduce this with the last release of bpython or master, with tmux 1.9a.

**Comment by sigmavirus24** [comment]
I'm on 

```
❯❯❯ tmux -V
tmux 1.9a
``

Also OSX using iTerm 2.

**Comment by thomasballinger** [comment]
It looks like your setup is rendering the `─` characters we use for horizontal lines as a [full-width](http://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) character instead of half-width, and something (zsh? tmux? iterm? bpython?) isn't accounting for this. The terminal width math in bpython assumes this character will render as half-width, but it looks like tmux is also confused because otherwise it would just wrap the characters. I don't really understand if this could matter, but what font are you using?

**Comment by thomasballinger** [comment]
I can reproduce this now: I get it when I select the "Treat ambiguous-width characters as double-width" option in iTerm 2.
![image](https://cloud.githubusercontent.com/assets/458879/7552050/8ffb750e-f66e-11e4-824d-136779da68b2.png)

I want to call this a tmux/iterm bug, I can reproduce it without bpython:
~~~
tomb@tom-mba ~$ python                  │omb@tom-mba ~$
Python 2.7.9 (default, Dec 15 2014, 10:1│
7:04)                                   │───────────────────[GCC 4.2.1 Compatible Apple LLVM 6.0 (cl│───────────────────ang-600.0.56)] on darwin                │───────────────────Type "help", "copyright", "credits" or "│
license" for more information.          │
>>> s = u'─'                             ──────────────────$>>> print s*50                          │─────────────────────────────────────────────────────────────────────
>>>                                     │
                                        │
~~~

**Comment by thomasballinger** [comment]
As a workaround, you can set the `unicode_box` config options under the `[general]` section to `False` and ordinary ascii characters will be used to render these boxes.

**Comment by sigmavirus24** [comment]
Sorry about that! I had just changed my font to [Input Mono](http://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputSans&width=300&weight=300&line-height=1.2&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&customize=please) and I only had that on one profile. Sorry for the noise @thomasballinger! Thanks for the help!

**Comment by thomasballinger** [comment]
No problem, we all got to learn things (:
