### ISSUE TITLE
Paste is slow with high CPU usage

### ISSUE THREAD

**Issue by goetzc** [bpython/bpython#546]
In my setup pasting text is really slow, with a high CPU usage. 
For example pasting this 10-line function takes like 10 seconds:

```python
def function_a():
    print('First line')
    print('Second line')
    print('Third line')

    for i in range(10):
        print(i)

    print('etc')
    print('etc')
    print('etc')
```

bpython version 0.14.1 on top of Python 3.4.3 /usr/bin/python

If I can provide you with more information, I would be happy to do so.

**EDIT**: KDE 4 (Qt 4.8.7), with Konsole 15.08 (KDE Frameworks 5.15, Qt 5.5.1). The same behavior using Python 3.5.

**Comment by thomasballinger** [comment]
@goetzc Is there anything else you can share about it?

This is normally prevented by noticing that so many bytes are coming in at once (more than 20 I believe) that this should be treated as a paste event, and the display not redrawn until all the byte have been read. Is there anything unusual about your setup?

**Comment by goetzc** [comment]
I just tested it in another setup (KDE Plasma 5) and the past function is fast.

The affected system uses KDE 4, maybe the text clipper (klipper) has something to do, or Konsole.
But both systems use the same Konsole version.

**Comment by thomasballinger** [comment]
https://github.com/bpython/bpython/pull/584 might fix this problem, @goetzc let me know if you try it out.

**Comment by goetzc** [comment]
With 0.14.2 and commit 64d875e merged with conflicts, I can tell it is now much faster!

**Comment by thomasballinger** [comment]
Great! This is probably too large a change to be a bugfix, so I'm marking this closed now and it will be fixed in the next release.
