### ISSUE TITLE
Arrow up doesn't show the previous commands anymore

### ISSUE THREAD

**Issue by kramer65** [bpython/bpython#557]
After upgrading (see my previous issue https://github.com/bpython/bpython/issues/556) my installation of bpython version 0.14.2 on top of Python 2.7.6 /usr/bin/python on a regular Ubuntu 14.04 server doesn't support using the arrow-up to show the previous commands anymore. 

Any idea how I can solve this?

**Comment by thomasballinger** [comment]
Could you try the following:
~~~
$ python -m curtsies.events
~~~
then press the up arrow key, and let me know what you see?

This could be a bug with Curtsies (and I need to implement a better fix for these keybindings, as suggested there)

**Comment by kramer65** [comment]
Thanks for your answer. To my surprise it now works again, without me even trying your fix.

Pretty weird, because as far as I know nothing changed in the meantime. The server didn't even restart.

Anyway. Big thanks to you guys for creating bpython. I use it every single day on the job on multiple servers. Pretty much the first thing I install.. :-)

**Comment by thomasballinger** [comment]
Great to hear, thanks!
