### ISSUE TITLE
Can't import boto

### ISSUE THREAD

**Issue by allblackt** [bpython/bpython#560]
Boto library can't be imported in bpython.

```
~/miniwork/tinysqs $ mkvirtualenv bpython-demo
New python executable in bpython-demo/bin/python
Installing setuptools, pip...done.
(bpython-demo) ~/miniwork/tinysqs $ pip install boto
Downloading/unpacking boto
  Downloading boto-2.38.0-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: boto
Successfully installed boto
Cleaning up...
(bpython-demo) ~/miniwork/tinysqs $ bpython 
>>> import boto
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: No module named boto
>>> exit()

(bpython-demo) ~/miniwork/tinysqs $ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>> 
```

I am working in a virtual environment, boto was installed via pip just before. Other libraries, such as requests, are importable.

**Comment by sebastinas** [comment]
Did you install bpython in the venv too?

**Comment by allblackt** [comment]
It worked after I installed bpython as a python package in my virtual env. I was running bpython from the installed ubuntu package. Is there such a big difference between those two?

**Comment by sebastinas** [comment]
The bpython executable from the Ubuntu package runs with /usr/bin/python ignoring the virtual env altogether.

**Comment by allblackt** [comment]
But other packages installed _only_ in the virtual environment are importable in bpython that is installed via ubuntu package. Why is that?

**Comment by giuliohome** [comment]
Thank you all! This solved also my issue with bpython-curses and venv on windows!
