### ISSUE TITLE
Suggestion: Install additional `console_scripts` with version suffixes

### ISSUE THREAD

**Issue by ulope** [bpython/bpython#562]
It would be great if bpython would additionally install it's cli entrypoint with version suffixes like the regular python interpreter does.
I.e.:

`bpython`
`bpythonX`
`bpythonX.Y`

This would be helpful especially when multiple versions of python are installed.

**Comment by thomasballinger** [comment]
For reference, IPython seems to do this with `ipythonX` but not `ipythonx.Y`

**Comment by sebastinas** [comment]
I'm closing this as wontfix. For some rational, see https://github.com/pytest-dev/pytest/issues/1632. If you need to run bpython with a specific Python version, `pythonX.Y -m bpython` is the recommended entrypoint.
