### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by kramer65** [bpython/bpython#565]
I'm trying to install bpython a a fairly fresh Ubuntu 14.04 box using `sudo pip install bpython`. But this ends in the errors below.

So I made sure I had `python-dev` installed and also `b﻿﻿uild-essential` is already the newest version. But the problem persists. Any idea what the problem could be?

c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-K8hLHA/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fHkdI7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-K8hLHA/cffi

**Comment by sebastinas** [comment]
Make also sure that you have libffi-dev installed or install the corresponding python-cffi packages.

**Comment by ikanobori** [comment]
You probably need to install the `libffi-dev` package through your package
manager.

**Comment by kramer65** [comment]
Thanks, installing `libffi-dev` indeed seemed to solve that. 

For future readers; after having fixed this, it started complaining about `openssl/aes.h`, so I installed `libssl-dev`, after which I could install bpython using the regular `sudo apt-get install bpython`.

Thanks for the help!

**Comment by marcel060** [comment]
python setup.py build
running build
running build_py
running build_ext
building 'cpyrit._cpyrit_cpu' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cpyrit/_cpyrit_cpu.c -o build/temp.linux-x86_64-2.7/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing -DVERSION="0.5.1" -maes -mpclmul
cpyrit/_cpyrit_cpu.c:39:10: fatal error: zlib.h: No such file or directory
   39 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
Failed to build; Compiling without AES-NI
building 'cpyrit._cpyrit_cpu' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cpyrit/_cpyrit_cpu.c -o build/temp.linux-x86_64-2.7/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing -DVERSION="0.5.1"
cpyrit/_cpyrit_cpu.c:39:10: fatal error: zlib.h: No such file or directory
   39 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                                            CAN SOMEONE HELP PLSS

**Comment by sebastinas** [comment]
This isn't the bug tracker for cpyrit.

If you are on a Debian-based system, install zlib1g-dev. Otherwise check which packages provides the zlib development files for your distribution.
