### ISSUE TITLE
MultiProcessing Problem

### ISSUE THREAD

**Issue by pdcxs** [bpython/bpython#566]
>>> from multiprocessing import Process
>>> def p() :
...     print("hello")
...     
... 
>>> a = Process(target=p)
>>> a.start()
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 249, in _bootstrap
    sys.stdin.close()
AttributeError: 'FakeStdin' object has no attribute 'close'

But in python it's OK.

**Comment by thomasballinger** [comment]
Adding a no-op FakeStdin.close() method seems to help, but I don't want this to appear to work if it doesn't really. I'll play a bit with this.

**Comment by thomasballinger** [comment]
This *particularly* bug is fixed by https://github.com/bpython/bpython/commit/427d3710ca6cbc033cc82648db42434baa6c056e although there are still issues with multiprocessing. The one I've found so far is stdout output from other processes being discarded.
