### ISSUE TITLE
output abnormal after reload(sys)

### ISSUE THREAD

**Issue by twz915** [bpython/bpython#567]
```
>>> import sys
>>> id(sys)
4545665968
>>> reload(sys)
>>> id(sys)
>>> 
```

bpython output is missing or abnormal. I've tested that original Python shell or IPython, both of them work fine.

**Comment by thomasballinger** [comment]
Whoa, pretty weird! Looks like reloading sys resets sys.stdout, so it's no longer our faked stdout.

**Comment by thomasballinger** [comment]
@twz915 Is there a use case for which this is important? It's the goal of bpython to behave the same as the interactive Python interpreter, so this is a bug, but one that would take some effort to fix.

If it's important, we could use a fake `reload()` function that sets `sys.stdout` and `sys.stderr` again, though this makes the magic we do less transparent.

**Comment by twz915** [comment]
Not that important, but useful when `setdefaultencoding`

        >>> import sys
        >>> sys.setdefaultencoding('gbk')
        Traceback (most recent call last):
          File "<input>", line 1, in <module>
        AttributeError: 'module' object has no attribute 'setdefaultencoding'
        >>> reload(sys)
        >>> sys.setdefaultencoding('gbk')
        >>> 

I like `bpython` very much, thanks for your hard work!

**Comment by twz915** [comment]
You could design the fake `reload()` just when `reload(sys)` sets `sys.out` and `sys.stderr` again. To other module except `sys`, it is just a wrapper which return original `reload` function.

**Comment by thomasballinger** [comment]
I'm on the fence, I think monkeypatching in a new reload function is reasonable, but found in the [reload docs](https://docs.python.org/2/library/functions.html#reload) is says

>It is generally not very useful to reload built-in or dynamically loaded modules. Reloading sys, __main__, builtins and other key modules is not recommended. In many cases extension modules are not designed to be initialized more than once, and may fail in arbitrary ways when reloaded.

https://github.com/bpython/bpython/pull/593 fixes this in the way described above.

**Comment by thomasballinger** [comment]
@sebastinas Any possible issues with this?

@twz915 I don't understand some of this: why is setdefaultencoding not available until sys is reloaded? Because I'm somewhat ignorant about encoding issues, could you describe why this is useful to you? Does #593 look good to you?

**Comment by twz915** [comment]
Thank you for all your efforts at first.
why is setdefaultencoding not available until sys is reloaded [copy from this answer](http://stackoverflow.com/a/3828742/2714931):
> This function is only available at Python start-up time, when Python scans the environment. It has to be called in a system-wide module, sitecustomize.py, After this module has been evaluated, the setdefaultencoding() function is removed from the sys module.


Generally speaking, we rarely use `reload(sys)`. A case is that we want to change default encoding is not utf-8 on some Operating System to utf-8 temporarily.

**Comment by thomasballinger** [comment]
In Python 3 this isn't a problem -- the attributes of sys are preserved on `importlib.reload(sys)`, and setdefaultencoding is gone anyway. Because of this I'm only monkeypatching reload in python 2.

**Comment by thomasballinger** [comment]
Current status of this: [PR 593](https://github.com/bpython/bpython/pull/593) fixes this, but we're not sure it's worth the complexity.

**Comment by thomasballinger** [comment]
closing as won't fix: this is only an issue in Python 2 when doing something not recommended by the docs, and my fix added too much complexity to the code. Thanks for reporting though!
