### ISSUE TITLE
functions without docstrings display encoding information

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#578]
(bpython)tomb@tom-mba ~$ bpython
    bpython version 0.15.dev177 on top of Python 2.7.10 /Users/tomb/.
    virtualenvs/bpython/bin/python2.7
    >>> def foo(): pass
    ...
    >>> foo(
    ┌──────────────────────────────────────────────────┐
    │ foo: ()                                          │
    │ # coding: UTF-8                                  │
    └──────────────────────────────────────────────────┘

in master, functions without docstrings are showing "# coding: UTF-8" as their docstring. Their `foo.__doc__` property is `None`, so it must be a display issue. This isn't a problem in 0.14.2.

**Comment by sebastinas** [comment]
This seems to be a Python 2.7 only issue. Can't reproduce it with Python 3.

**Comment by sebastinas** [comment]
Adding a second newline in `bpython.reply.Interpreter.runsource` fixes this (but breaks a test case that relies on some line numbers).

**Comment by thomasballinger** [comment]
Ah I didn't understand this before but now see now why that helps, because

>If there is no docstring, pydoc tries to obtain a description from the block of comment lines just above the definition of the class, function or method in the source file, or at the top of the module (see inspect.getcomments()).

from https://docs.python.org/2/library/pydoc.html

This seems like a good way to fix this, as it just requires subtracting two lines instead of one.
