### ISSUE TITLE
None doesn't always print

### ISSUE THREAD

**Issue by kramer65** [bpython/bpython#590]
Today I was playing with a Python dict in bpython and I found something weird:

```
>>> print {}.get('non-existant-key')

>>> a = {}.get('non-existant-key')
>>> print a
None
>>>
```

Why does the repl print an empty space with the first print and "None" after taking the step of storing the value in the variable `a`? The thing it tries to print is the same in both cases, so why is there a difference?

Although it's not really a big problem I was confused as to what was wrong and if there was a difference in result. In the regular Python repl it works as expected. 

Since it's not a very big problem this is just a tip to make bpython even more awesome than it already is. :-)

**Comment by thomasballinger** [comment]
Thanks for submitting this @kramer65. I tried out a few more, it seems like:
* `print None` doesn't work *unless it's the first line executed*
* `print (None)` doesn't ever work (even if it's the first line executed)
* `a = None; print a` always works

I'm taking a look now.

    (bpython)tomb@tom-mba (master) bpython$ bpython
    bpython version 0.15.dev213 on top of Python 2.7.10 /Users/tomb/.virtualenvs/bpython/bin/python2.7
    >>> print None
    None
    >>> print None

    >>> a = None
    >>> print a
    None
    >>> print a
    None
    >>>

**Comment by thomasballinger** [comment]
This is terrible and my fault. The issue is in the caching of lines in Curtsies terminal rendering. https://github.com/thomasballinger/curtsies/issues/84

**Comment by thomasballinger** [comment]
I've fixed this in Curtsies. If you're using bpython 0.14.x (the latest released version) and would like this fixed, upgade Curtsies; if using pip, it's:

    pip install 'curtsies==0.1.21'

If you're using master, you can just upgrade to the latest Curtsies version, now 0.2.4:

    pip install --upgrade curtsies --no-cache-dir
