### ISSUE TITLE
Installation on Ubuntu 14.04 with pip needs extra ndg-httpsclient and pyasn1

### ISSUE THREAD

**Issue by kramer65** [bpython/bpython#595]
When installing a new Ubuntu 14.04 server I always install bpython as one of the first things. I can do it using `sudo apt-get install ` which installs bpython 0.12.x. 

That version works, but I like the newer version 0.14.2 better. So I use `sudo pip install bpython==0.14.2`. After doing that I always manually need to install `ndg-httpsclient` and `pyasn1` to get it working. I just wonder whether why those are apparently not listed as dependencies and automatically installed with bpython. 

Maybe a tip to make installing the latest version via pip a bit easier.. :-)

**Comment by sebastinas** [comment]
http://bpython-interpreter.org/known-issues-and-faq.html
