### ISSUE TITLE
-bash: /usr/bin/bpython: No such file or directory after upgrade to version 0.14.2

### ISSUE THREAD

**Issue by kramer65** [bpython/bpython#600]
Bpython was working fine on my Ubuntu 14.04 server, but I was at version 0.12 and I enjoy the new features in 0.14.2 on another server so I upgraded using

    sudo pip install bpython==0.14.2

When I run `bpython` after that, I get

    $ bpython
    -bash: /usr/bin/bpython: No such file or directory

I solved it by running 

    sudo ln /usr/local/bin/bpython /usr/bin/bpython

But I thought I would mention it here because this maybe uncovers a bug for you guys?

Cheers!

**Comment by kramer65** [comment]
Nevermind, I just solved it by running



But maybe this

**Comment by sebastinas** [comment]
If that's a bug, it is not fixable in bpython. There is something wrong in the interaction of your OS and pip or your $PATH is incomplete.
