### ISSUE TITLE
question: bpython in flask application context

### ISSUE THREAD

**Issue by item4** [bpython/bpython#604]
I want to use bpython in flask application context.

I wrote this code.

```py
config = read_config() # just gen config
app = create_app(config) # just return Flask(__name__).config.update(config)
with app.app_context():
    import bpython
    bpython.embed(locals_=dict(app=app))
```

But it did not work correctly.

```pycon
>>> from flask import current_app
>>> current_app.config
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    current_app.config
  File "/Users/item4/.virtualenvs/*/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/item4/.virtualenvs/*/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/Users/item4/.virtualenvs/*/lib/python3.5/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
```

How can I embed bpython in flask application context?

**Comment by thomasballinger** [comment]
Hm, it looks like this has to do with Flask's [Context Locals](http://werkzeug.pocoo.org/docs/0.11/local/#module-werkzeug.local) which are carefully not shared between threads **or greenlets**, which is the relevant bit for bpython.

Unfortunately the curtsies bpython frontend creates a new greenlet *every time it runs code*, so even if you were to run `app.app_context().__enter__()` as soon as bpython started, code run on another repl input would occur in a new greenlet, and the app context would have been cleaned up by this point.

I would suggest using the old bpython curses interface like so:

    from flask import Flask
    from bpython.cli import main as oldbpython

    app = Flask('hello')
    with app.app_context():
        oldbpython(locals_={'app': app}, args=['-i', '-q'])

**Comment by matannoam** [comment]
This is very disappointing. What I am understanding is that I can no longer use bpython to work with Flask applications.

**Comment by thomasballinger** [comment]
Or you'll need to use bpython-curses, which is the old frontend - it's "bpython-curses" from the command line, or in Python code as described above.

**Comment by thomasballinger** [comment]
(these are included in an installation of bpython)
