### ISSUE TITLE
<Delete> key does nothing in iTerm2 (MacOS)

### ISSUE THREAD

**Issue by krigstask** [bpython/bpython#613]
That's it, it stopped working a while ago, I haven't really noticed what have I done (it has to work earlier).

iTerm2 sends `\033[3~` for *\<Delete>* here (if I'm determining this right), and it works fine with other shells on my box.  Probably *curtsies* issue, but I decided to file issue here.

**Comment by thomasballinger** [comment]
Thanks @krigstask, I'll take a look after PyCon.

**Comment by thomasballinger** [comment]
I believe this was fixed by https://github.com/bpython/bpython/pull/611
