### ISSUE TITLE
bpython run greenlet bug

### ISSUE THREAD

**Issue by elvis-macak** [bpython/bpython#620]
```
from greenlet import getcurrent
getcurrent()
getcurrent()
getcurrent()
```

run the code above, even I call `getcurrent` for 3(or more) times, it will get the same obj in `python` shell and `ipython` shell, but it failed in `bpython`, it'll give more than one different greenlet, so it'll cause bugs like [flask context error](https://github.com/smurfix/flask-script/issues/155)

**Comment by elvis-macak** [comment]
similar like https://github.com/bpython/bpython/issues/604, 
but when run `create_app().app_context().push()` it'll failed, running a `with` block works well

**Comment by thomasballinger** [comment]
Like #604, I suggest using the `$ bpython-curses` command as a workaround (another executable also installed with `$ bpython`). As for fixing, this would take a rewrite of code execution engine, and if that happens it'll be to make code run in a separate process.

**Comment by elvis-macak** [comment]
But running the following code, get different result. While the [`bpython.embed`](https://github.com/bpython/bpython/blob/master/bpython/__init__.py#L34) does nothing
```
from bpython.cli import main
main(['-i', '-q'], None, None)
--------------
>>> from greenlet import getcurrent
>>> getcurrent()
<greenlet.greenlet object at 0x2af7a50>
>>> getcurrent()
<greenlet.greenlet object at 0x2af7af0>
>>> getcurrent()
<greenlet.greenlet object at 0x2af7c30>
>>> getcurrent()
<greenlet.greenlet object at 0x2af7cd0>
```

```
from bpython import embed
embed()
-----------
>>> from greenlet import getcurrent
>>> getcurrent()
<greenlet.greenlet object at 0x1f32d70>
>>> getcurrent()
<greenlet.greenlet object at 0x1f32d70>
>>> getcurrent()
<greenlet.greenlet object at 0x1f32d70>
>>>
```

**Comment by elvis-macak** [comment]
I save the code as a single `.py` file, and run it using original python shell directly.
