### ISSUE TITLE
Keys F1-4 don't work

### ISSUE THREAD

**Issue by Murlocks** [bpython/bpython#626]
When I press F keys 1-4, they simply output a tilde and do not perform their default actions. The other F keys seem to work fine.

I am using urxvt under arch linux. My keyboard settings seem to be fine, and my terminal picks up F1 under other applications (ncmpcpp) so I believe that is not the issue. Any suggestions? I can always rebind what I need, but I would like to see if there are any possible fixes first.

**Comment by thomasballinger** [comment]
Bpython uses Curtsies which (somewhat unfortunately) has custom identification. Try

    python -m curtsies.events

and use the F keys that don't work and post the result here.

**Comment by Murlocks** [comment]
Looks like that was the problem. Here are the logs:

b'\x1b[11~'
unknown!!!
Unidentified character sequence!
type 'ok' to prove you're not pounding keys ok
Press the key that produced b'\x1b[11~' again please
Describe in English what key you pressed: F1
Thanks! Please open an issue at https://github.com/thomasballinger/curtsies/issues
or email thomasballinger@gmail.com. Include this terminal history or keylog.txt.
You can keep pressing keys
---
b'\x1b[12~'
unknown!!!
Unidentified character sequence!
type 'ok' to prove you're not pounding keys ok
Press the key that produced b'\x1b[12~' again please
Describe in English what key you pressed: F2
Thanks! Please open an issue at https://github.com/thomasballinger/curtsies/issues
or email thomasballinger@gmail.com. Include this terminal history or keylog.txt.
You can keep pressing keys
---
b'\x1b[13~'
unknown!!!
Unidentified character sequence!
type 'ok' to prove you're not pounding keys ok
Press the key that produced b'\x1b[13~' again please
Describe in English what key you pressed: F3     
Thanks! Please open an issue at https://github.com/thomasballinger/curtsies/issues
or email thomasballinger@gmail.com. Include this terminal history or keylog.txt.
You can keep pressing keys
---
b'\x1b[14~'
unknown!!!
Unidentified character sequence!
type 'ok' to prove you're not pounding keys ok
Press the key that produced b'\x1b[14~' again please
Describe in English what key you pressed: F4
Thanks! Please open an issue at https://github.com/thomasballinger/curtsies/issues
or email thomasballinger@gmail.com. Include this terminal history or keylog.txt.
You can keep pressing keys
---
b'\x1b[15~'
<F5>

**Comment by thomasballinger** [comment]
I've added these to Curtsies, if it's convenient could you check that they're fixed before I release it? `pip install --upgrade git+https://github.com/thomasballinger/curtsies.git`

**Comment by Murlocks** [comment]
I've tested it out and the keys are now being read in curtsies:

```
b'\x1b[11~'
KEY_F(1)
---
b'\x1b[12~'
KEY_F(2)
---
b'\x1b[13~'
KEY_F(3)
---
b'\x1b[14~'
KEY_F(4)
---
b'\x1b[15~'
<F5>
```
However, bpython still doesn't seem to pick them up under the default config.

**Comment by thomasballinger** [comment]
Whoops, dumb mistake on my part. Would you try it again?

**Comment by Murlocks** [comment]
Works perfect now, thanks a lot for the speedy fix.

**Comment by thomasballinger** [comment]
reopening because there hasn't been a Curtsies release with this fix in it yet, so reminder that needs to be done.

**Comment by sebastinas** [comment]
A new version of curtsies has been released in the meantime.
