### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by blueyed** [bpython/bpython#635]
Please consider creating a new release.

I have noticed that there are some fixes already, and the packaging is a bit inconsistent currently:
https://github.com/bpython/bpython/releases only has 0.14.1.
https://pypi.python.org/pypi/bpython/0.15 has 0.15.0, but it gets extracted as 0.15.

**Comment by thomasballinger** [comment]
pinging @ikanobori for this

**Comment by thomasballinger** [comment]
ping @ikanobori

**Comment by sebastinas** [comment]
@thomasballinger Could you please update / check the Changelog?

**Comment by ikanobori** [comment]
We've tried to discuss this a few times on IRC. I can do a new release but
need the go ahead from Thomas/Sebastian to do so :)

**Comment by sebastinas** [comment]
@thomasballinger Please review the changelog and add anything that's missing.

**Comment by ikanobori** [comment]
Version 0.16 has been released on PyPi at: https://pypi.python.org/pypi?name=bpython&version=0.16&:action=display

Marking this as closed.
