### ISSUE TITLE
Keyboard input problems in 0.16

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#644]
>Hi *,

>I've installed curtsies-0.2.10 and bpython-0.16 (Gentoo linux, python-3.5.2). After I start bpython, the keyboard no longer works in this window: I try to type something, but nothing appears; Enter does not work. What can be the reason?

>bpython-0.15 with curtsies-0.2.9 worked fine.

**Comment by grozin** [comment]
Sorry, this was my fault. Please close this bug.

I upgraded several libraries which are used by python-3.5.2, in particular readline to 7.0, which is binary incompatible with older versions. After that python itself did not work properly. Recompiling python has solved the problem. bpython has nothing to do with it.

**Comment by thomasballinger** [comment]
Whew, good to hear. Thanks for checking in!
