### ISSUE TITLE
python3 cant start after install

### ISSUE THREAD

**Issue by kobzar** [bpython/bpython#645]
Hello all. 
Bpython is wonderful instrument. 
with last version of python2 all working fine
pip install bpython
bpython - OK
But in python3 (Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) ) have a trouble with start
pip3 install bpython - OK
bpython - command not found

**Comment by sebastinas** [comment]
Could you please attach a verbose output of `pip3 install bpython`?

**Comment by kobzar** [comment]
Sorry, ,it was my mistake. 
I'm forgot add python3 to my $PATH
After that - all working fine.

**Comment by sebastinas** [comment]
Great!
