### ISSUE TITLE
Option-delete doesn't delete a left paren

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#655]
On line like
~~~
>>> (( asdf a sdf
>>>         lots of space
~~~
pressing option-delete repeatedly doesn't delete the opening parens or leading spaces

**Comment by Kashyap12** [comment]
hi @thomasballinger , can I take this up?

**Comment by thomasballinger** [comment]
@Kashyap12 Sure, feel free! It's all first come, first served. Let me know if you want to chat about it at all.

**Comment by thomasballinger** [comment]
Here's some code that could be added to the test at https://github.com/bpython/bpython/blob/a40c8635a7022bb32beab1de42f058610e0a186f/bpython/test/test_manual_readline.py#L227
to test this behavior:

        self.try_stages_kill([
            ' (( asdf |',
            ' (( |',
            '|'
            ], delete_word_from_cursor_back)

**Comment by thomasballinger** [comment]
My goal had been for this to match whatever it is that option backspace does on my mac, but a version of that that's more useful for Python code would be fine too.

**Comment by shreab373** [comment]
can i try this?

**Comment by thomasballinger** [comment]
Sure, that'd be great!
