### ISSUE TITLE
 cc1: some warnings being treated as errors     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1     

### ISSUE THREAD

**Issue by duqow1** [bpython/bpython#666]
I trying to install snoopy-ng in ubuntu server,but at the last stage this is what I get help please thanks

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-swH988/pylibpcap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rvbmiX-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-swH988/pylibpcap/

**Comment by sebastinas** [comment]
I think you found the wrong bug tracker. `bpython` has nothing to do with `pylibpcap`.
