### ISSUE TITLE
Is there a way to know whether I'm using bpython?

### ISSUE THREAD

**Issue by laike9m** [bpython/bpython#669]
`ipython` can be detected by checking `__IPYTHON__`'s existence. What to do in bpython?

**Comment by sebastinas** [comment]
There is no official way, but checking if the type of `help` is some `bpython` class should do the trick.

**Comment by laike9m** [comment]
http://stackoverflow.com/questions/42765320/how-to-inspect-the-type-of-repl-youre-using/42818291#42818291
