### ISSUE TITLE
bpython breaks line with ANSI escape code

### ISSUE THREAD

**Issue by laike9m** [bpython/bpython#670]
This can be easily reproduced by typing

```
print('\033[31mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[3
1mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[3
1mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m\033[31mOK\033[0m')
```

In bpython
![image](https://cloud.githubusercontent.com/assets/2592205/24078003/758e69bc-0c9a-11e7-8dde-ce21db6f3969.png)

In Python
![image](https://cloud.githubusercontent.com/assets/2592205/24078004/831b6b2a-0c9a-11e7-8dba-035cd6a91684.png)

I guess when calculating the length of output, bpython counts all chars, but not all chars are visible, thus leading to this bug.

**Comment by laike9m** [comment]
While I managed to get over the previous issue:
https://github.com/thomasballinger/curtsies/issues/97

I really can't get things to work without this being fixed. I'd appreciate if you could fix it.

**Comment by laike9m** [comment]
@sebastinas @thomasballinger What do you think? Since no other REPLs has this issue, the inconsistency between them and bpython certainly brings undesired behavior to some libraries, which I think is a serious problem.

**Comment by sebastinas** [comment]
Handling of escape characters happens in curtsies. So while this certainly is an issue that affects bpython, it needs to be fixed in curtsies.

**Comment by thomasballinger** [comment]
Thanks to @ata2001 the second issue you mentioned https://github.com/thomasballinger/curtsies/issues/97 is fixed. Fixing length issues is possible and were it to happen via a combination of using the [wcwidth](https://github.com/jquast/wcwidth)-based width of a curtsies FmtStr. https://github.com/thomasballinger/curtsies/issues/8 is the most relevant issue for this, we should consider this bpython issue blocked on that.

**Comment by laike9m** [comment]
Thanks guys. Looking forward to a new release. 😄

**Comment by ata2001** [comment]
Test cases would not be bad for this, but I'd need some help with doing that.
