### ISSUE TITLE
Automatically 'enter bpython' when running from set_trace()

### ISSUE THREAD

**Issue by lwm** [bpython/bpython#671]
I normally just drop a debugging statement into my code like:

```python
import bpdb; bpdb.set_trace()  # noqa
```
And then see the following:

```
...
Use "B" to enter bpython, Ctrl-d to exit it.
>>>
```

Is there some configuration that will automatically enter me into bpython? I was fishing around the issues and documentation but couldn't see this anywhere? I'd be happy to dig into adding this if it is not already configurable.

Thanks for bpython, it's great :+1:

**Comment by thomasballinger** [comment]
Embed is supposed to do this (`from bpython import embed`) but I believe it doesn't fix up local variables, though it should - instead you have to pass them in.

**Comment by sebastinas** [comment]
I don't think we should change the behavior of `bpdb.set_trace()`. The current behavior is in line with `pdb.set_trace()`, i.e. it drops you in the debugger.

**Comment by lwm** [comment]
> but I believe it doesn't fix up local variables

Oh, that's a shame. Not much use without those variables :|

> I don't think we should change the behavior of bpdb.set_trace()

Could we create an optional flag? Or some other function?

**Comment by thomasballinger** [comment]
I think we should just fix embed! It should behave like IPython's embed, doing exactly what you're asking for. Looks like there's an old issue: https://github.com/bpython/bpython/issues/397

**Comment by sebastinas** [comment]
This issue doesn't have anything to do with embed, right? It's about the behavior of `bpdb` when the debugger is started. We will have to re-implement some parts of Python's `pdb` to directly drop to bpython instead of first displaying the debugger UI.

**Comment by thomasballinger** [comment]
Ah yeah I guess not, I was restating @lwm's issue as "I want to drop in a line of code and start a bpython session there," since they want to jump straight to bpython, and thinking they could use `import bpython; bpython.embed()` instead of bpd.

**Comment by lwm** [comment]
Looks like https://github.com/bpython/bpython/issues/397 is what we want here then.
