### ISSUE TITLE
Support .pdbrc in bpdb (or variation)

### ISSUE THREAD

**Issue by Solanar** [bpython/bpython#677]
I was trying to add autocomplete to bpdb, I know it already works in bpython.

See https://github.com/python-git/python/blob/master/Lib/pdb.py#L78-L95 for `.pdbrc` implementation

I'm wondering why these lines aren't in https://github.com/bpython/bpython/blob/master/bpdb/debugger.py

Was there a reason this isn't supported? Possibly with it's own .rc eg `.bpdbrc`

So I just stepped through the code and since bpdb extends pdb, it is loading `.pdbrc`, but it's effects aren't seen in bpdb, at least for me.

Ah, line 36 in bpdb/debugger.py sets `self.rcLines = []` which means that `.pdbrc` won't be loaded.

My .pdbrc contains:

```python
import rlcompleter

print('pdb autocomplete')
import pdb  # just in case
pdb.Pdb.complete = rlcompleter.Completer(locals()).complete
```

Commenting out line 36 from dpdb/debugger.py properly loads my `.pdbrc` Can this line be commented out, or a variation of pdb.py's code be added to load a `.bpdbrc`?

I'm on Windows 10 using MinGW64 provided by git, Python 3.5, bpython 0.14.2

**Comment by thomasballinger** [comment]
Thanks for pointing this out, I agree we shouldn't ignore rc files. This could potentially break some things, but I think the right thing to do here is to treat bpdb like it's exactly pdb and use that rc file because we haven't added sufficient features to it to consider it a separate thing.

**Comment by Solanar** [comment]
Thanks for looking into it. Now I'll have to figure out how to upgrade from 0.14.2, but that's another issue.
