### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nottakenyet** [bpython/bpython#683]
Running a pip install from terminal yields the following:
...
Installing collected packages: blessings, wcwidth, curtsies, greenlet, six, pygments, bpython
  Running setup.py install for blessings ... done
  Running setup.py install for greenlet ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-2mniclo2/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-m89x38fv-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-armv7l-3.6
    arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -I/data/data/com.termux/files/usr/include/python3.6m -c greenlet.c -o build/temp.linux-armv7l-3.6/greenlet.o
    unable to execute 'arm-linux-androideabi-clang': No such file or directory
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-2mniclo2/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-m89x38fv-record/install-record.txt --single-version-externally-managed --com

I installed libllvm prior (gcc unavailable anymore)
Is it my system or the code?

**Comment by sebastinas** [comment]
You'll need clang. libllvm is not enough.
