### ISSUE TITLE
Get aware of `virtualenv`

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#7]
I don't know why… but bpython does not use modules installed in a virtual python environment (http://pypi.python.org/pypi/virtualenv)

It would be very cool if bpython recognizes those.

(See http://webshox.org/~shoxi/bpython.ogv for an example)

---
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/7
- Originally Reported By: [Christopher Grebs](http://bitbucket.org/EnTeQuAk)
- Originally Created At: 2009-06-02T15:30:54.702

**Comment by TheSeriousProgrammer** [comment]
it would be nice if the above mentioned fix is mentioned in ReadMe
