### ISSUE TITLE
Performance regression due to width_aware_slice

### ISSUE THREAD

**Issue by yangle** [bpython/bpython#717]
Apparently ef917412711fe55fe64325dbb2c61872914d4ee0 introduced a significant performance regression when printing a long output.  (The precise commit was pinned down through git bisect.)

To reproduce it, run
```
$ bpython
bpython version 0.18.dev15 on top of Python 2.7.13 /tmp/bpython/.venv/bin/python2
>>> ' '.join(map(str, xrange(10000)))
(hangs)
```

After reverting ef917412711fe55fe64325dbb2c61872914d4ee0, printing `' '.join(map(str, xrange(10000)))` takes less than a blink.

**Comment by yangle** [comment]
Just realized that this is a duplicate of #703.

**Comment by sebastinas** [comment]
Let's continue that in #703.
