### ISSUE TITLE
End of line cut off after saving tmp file

### ISSUE THREAD

**Issue by waltsims** [bpython/bpython#727]
One line with a long data path was cut off after I edited the history file and saved it back to the tmp file.  Is this a known bug that I missed in the issues? Maybe it has something to do with line wrapping?

**Comment by ikanobori** [comment]
Can you give me some more direct instructions on how to reproduce this so I can take a look?

**Comment by thomasballinger** [comment]
Repro:
* start bpython in a narrow terminal
* `>>> s = 'very long string literal that is going to be cut off if you make your terminal very narrow'`
* F7
* edit the string
* save
* observe error on reevaluation

**Comment by ikanobori** [comment]
@thomasballinger I know you were taking a look as per IRC, did you make any progress on this?

**Comment by sebastinas** [comment]
FWIW, the issue is in `bpython.curtsiesfrontend.BaseRepl.send_session_to_external_editor`. It reconstructs the user input from `self.getstdout()` instead of the history. Thus long lines, that are a single input line, but require multiple lines to be displayed, contain extra line breaks.
