### ISSUE TITLE
Fails to run using 'Terminal' on Ubuntu 17.10 within a VMWare Fusion VM

### ISSUE THREAD

**Issue by recvfrom** [bpython/bpython#732]
Every time I run 'bpython' from within a 'Terminal' terminal window in a Ubuntu 17.10 VMWare Fusion VM, I immediately get the following stack trace:

```
bpython version 0.17 on top of Python 2.7.14 /usr/bin/python
Traceback (most recent call last):
  File "/usr/bin/bpython", line 11, in <module>
    load_entry_point('bpython==0.17', 'console_scripts', 'bpython')()
  File "/usr/lib/python2.7/dist-packages/bpython/curtsies.py", line 188, in main
    with repl.window as win:
  File "/usr/lib/python2.7/dist-packages/curtsies/window.py", line 255, in __enter__
    self.top_usable_row, _ = self.get_cursor_position()
  File "/usr/lib/python2.7/dist-packages/curtsies/window.py", line 298, in get_cursor_position
    c = retrying_read()
  File "/usr/lib/python2.7/dist-packages/curtsies/window.py", line 292, in retrying_read
    'cursor get pos response read interrupted'
ValueError: cursor get pos response read interrupted
^[[39;1Rzelda@hyrule:~$ ;1R
```

strace indicates the following:

```
write(1, "\33[6n", 4)                   = 4
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
read(0, 0x55bd32088310, 1024)           = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGINT, {sa_handler=0x55bd30900bf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbda2f55150}, {sa_handler=0x55bd30900bf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbda2f55150}, 8) = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(2, "Traceback (most recent call last):\n", 35Traceback (most recent call last):
```

Making the following change in /usr/lib/python2.7/dist-packages/curtsies/window.py seems to resolve the issue:

```python
class CursorAwareWindow(BaseWindow):
...
    def get_cursor_position(self):
    ...
        def retrying_read():
            while True:
                try:
                    c = in_stream.read(1)
                    ...
                except IOError:
                    #raise ValueError(
                    #    'cursor get pos response read interrupted'
                    #)
                    # find out if this ever really happens - if so, continue
                    continue
```

bpython doesn't give me any issues when using 'Terminal' on a desktop 17.10 Ubuntu machine, and running python via another terminal program (Terminator) in that same VM works fine as well... It sounds like some race condition with reading from in_stream.

Since I'm not sure what could be causing this, here's as much info as I can think to include:
Host OS: Mac OS X 10.13.3 (17D102)
VMWare Fusion Professional Version 10.1.1 (7520154)
Guest OS: Ubuntu 17.10 running x86_64 kernel version 4.13.0-32-generic
VMWare Tools Installed: 10.2.0.7047 (build-7259539)

**Comment by thomasballinger** [comment]
Cool, sounds like this does happen :)

**Comment by thomasballinger** [comment]
We should leave this open until we do a new Curtsies release.

**Comment by recvfrom** [comment]
@thomasballinger I think this was the issue: https://unix.stackexchange.com/q/437409/284350

An application I was using was setting STDIN to non-blocking mode and not resetting it to blocking mode upon exiting... it turns out that bash on Ubuntu doesn't (wouldn't?) automatically reset it either, so STDIN would have non-blocking semantics for other applications launched in that same terminal window.  This breaks lots of other applications as well, as you can see from the examples in the stackexchange post.

**Comment by thomasballinger** [comment]
Huh interesting! Thanks for checking in with this.
