### ISSUE TITLE
"Incr Search Mode" newline on every new character

### ISSUE THREAD

**Issue by dylnmc** [bpython/bpython#733]
something is wrong with either ansi escapes or curses in Incr Search Mode. if I press <kbd>alt</kbd> <kbd>r</kbd> to go into Incr Search Mode, then I type something like `from` to bring up the last `from … impoort …` and I see four "Incr search mode"s on separate lines (one pops up every key press).

It did not used to do this.

![screenshot from 2018-02-28 18-50-13](https://user-images.githubusercontent.com/7635158/36819640-3ea17aaa-1cb8-11e8-8b41-ac4f11fc5741.png)

**Comment by thomasballinger** [comment]
Thanks for reporting
