### ISSUE TITLE
Commands not available in bpython-urwid/bpython-curses

### ISSUE THREAD

**Issue by tbabej** [bpython/bpython#736]
Hi,

in `bpython-urwid` or `bpython-curses` the "external editor", the "toggle file watch" and "reimport" commands (F5, F6 and F7) are not available. I'm using no custom configuration.

Is this expected?

**Comment by thomasballinger** [comment]
Yep :/, these aren't implemented there. I think we'd be open to adding them, in particular I'd appreciate the external editor for bpython-urwid because I know people that use that one.
