### ISSUE TITLE
Fix handling of double-column characters

### ISSUE THREAD

**Issue by BenWiederhake** [bpython/bpython#749]
This is probably an issue with curtsies, but until I'm sure I want to report it here first:

Steps to reproduce: Enter something like `'間'.isalnum()`, then move the cursor back (left arrow key) such that `a` is the next character, and insert an `x`.
Expected behavior: Visually it looks like we're about to insert an `x` between `is` and `alnum`.  So I would expect the line to say `isxalnum`.
Actual behavior: It now says `'間'.isaxlnum()`, with the next character seemingly being the `x`.

Try this out with `y` instead of `間` to see the expected behavior.

I may have broken this in the patch to #703, I'm not sure.

The pun ("間" meaning "between") is entirely coincidental, but I like it, and I'm keeping it.

**Comment by rybarczykj** [comment]
Resolved with PR #817! And a current PR is in progress to fix line wrapping with double-column chars.

**Comment by sebastinas** [comment]
Fixed thanks to @rybarczykj
