### ISSUE TITLE
strange tab behavior

### ISSUE THREAD

**Issue by ljcnaix** [bpython/bpython#755]
print a format string in bpython:

    bpython version 0.17.1 on top of Python 3.6.7 /tmp/py3/bin/python3
    >>> print('a\tbb\tccc\tdddd\teeeee\tffffff\tggggggg\thhhhhhhh\t')
    a     bb      ccc     dddd    eeeee   ffffff  ggggggg hhhhhhhh        
    >>> print('a\tbb\tccc\tdddd\teeeee\tffffff\tggggggg\thhhhhhhh\t')
    a  bb      ccc     dddd    eeeee   ffffff  ggggggg hhhhhhhh        
    >>> print('a\tbb\tccc\tdddd\teeeee\tffffff\tggggggg\thhhhhhhh\t')
    a bb      ccc     dddd    eeeee   ffffff  ggggggg hhhhhhhh        
    >>> print('a\tbb\tccc\tdddd\teeeee\tffffff\tggggggg\thhhhhhhh\t')
    a        bb      ccc     dddd    eeeee   ffffff  ggggggg hhhhhhhh        
    >>> print('a\tbb\tccc\tdddd\teeeee\tffffff\tggggggg\thhhhhhhh\t')
    a        bb      ccc     dddd    eeeee   ffffff  ggggggg hhhhhhhh        
    >>> exit()

same format string with different print result.

**Comment by thomasballinger** [comment]
Wacky! I can't reproduce this, which terminal emulator is this with?

**Comment by sebastinas** [comment]
I cannot reproduce the issue. If it still exists, please provide the info @thomasballinger requested.
