### ISSUE TITLE
Why is bpython contacting twitter?

### ISSUE THREAD

**Issue by diamond-lizard** [bpython/bpython#757]
When I strace bpython I see that it's contacting twitter.  Why is this happening?

Also, on occasion, when I start bpython it causes a huge amount of disk activity.  I haven't tracked down the reason for that yet, but that along with the twitter access (or any not-explicitly requested network access) by bpython is concerning.

**Comment by ikanobori** [comment]
Hi, bpython does not use Twitter nor should it contact Twitter at all. Can you share your strace output and tell me where you got your bpython installation from?

**Comment by diamond-lizard** [comment]
According to portage, my OS's (Gentoo's) package manger, /usr/lib/python-exec/python3.6/bpython is part of Gentoo's bpython package install.

I've had a second, closer look at the strace output, and it looks like I mistook an example in a read of /usr/lib64/python3.6/site-packages/urllib3/__pycache__/poolmanager.cpython-36.pyc for an actual connection to twitter.

Sorry for the false alarm.  I am going to close this issue.
