### ISSUE TITLE
bpython returns wrong error code on exit()

### ISSUE THREAD

**Issue by devgar** [bpython/bpython#761]
That simple, and seems that bpython always passes 1 as exit code to the parent interpreter regardless of the value used as argument.

![captura de pantalla 2019-01-03](https://user-images.githubusercontent.com/2792291/50631559-0a364680-0f45-11e9-8819-3a7f1c44ad63.png)

I found a previous related issue that was solved #227

**Comment by sebastinas** [comment]
Fixed in 68df142edb1f9adb0b348374277211e1802de39c.
