### ISSUE TITLE
autocomplete possible for function declarations?

### ISSUE THREAD

**Issue by zachvalenta** [bpython/bpython#766]
Is it possible to use autocomplete to redeclare functions?

<img width="454" alt="screen shot 2019-02-25 at 11 43 44 am" src="https://user-images.githubusercontent.com/11388735/53353483-ccc1ba00-38f2-11e9-8caa-f15896db158e.png">

`bpython` seems to know that I've recently declared a function `cool()` and that it takes `**kwargs`; it would be awesome if I could just tab over to complete.

**Comment by thomasballinger** [comment]
You can press right arrow, ctrl-f, or ctrl-e to complete code suggested from history like `def cool(**kwargs)` here - is that what you'd like?

**Comment by zachvalenta** [comment]
bingo! my bad, I poked around the docs and couldn't find this.
