### ISSUE TITLE
pypi metadata points at (defunct) www. subdomain

### ISSUE THREAD

**Issue by glyph** [bpython/bpython#772]
I went to https://pypi.org/project/bpython/0.18/

Clicked on "homepage"

![image](https://user-images.githubusercontent.com/716529/55585240-11ebbf80-56db-11e9-84dc-772a47f80190.png)

**Comment by ikanobori** [comment]
Hey @glyph I should've added the necessary redirects to go from www. -> non-www. it was probably not migrated with a server move.

My curl seems to show me it's working (silly HSTS), how is it for you?

**Comment by glyph** [comment]
Yep, clicking the link seems to do the right thing now. Thanks!
