### ISSUE TITLE
bpython not installing on Termux

### ISSUE THREAD

**Issue by arqeco** [bpython/bpython#779]
Trying to install bpython on Termux on Android gives an error:

pip install  bpython

...
Running setup.py install for curtsies ... done
  Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-jvk2v9ev/greenlet/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-jvk2v9ev/greenlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-yv9owuui/install-record.txt --single-version-externally-managed --compile
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-jvk2v9ev/greenlet/
    Complete output (9 lines):
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-armv7l-3.7
    arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -I/data/data/com.termux/files/usr/include/python3.7m -c greenlet.c -o build/temp.linux-armv7l-3.7/greenlet.o
    unable to execute 'arm-linux-androideabi-clang': No such file or directory
    error: command 'arm-linux-androideabi-clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-jvk2v9ev/greenlet/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-jvk2v9ev/greenlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-yv9owuui/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by sebastinas** [comment]
You'll need a compiler and whatever else greenlet requires to build. Alternatively, you can probably cross-compile greenlet for Android.
