### ISSUE TITLE
help() function prints nothing for specific arguments

### ISSUE THREAD

**Issue by kylepollina** [bpython/bpython#789]
Overview: using help(print) and help(iter) does not print the help pages for these functions within the bpython interpreter.

Expected Behavior: typing help(print) or help(iter) prints the help pages for these two functions

OS: Manjaro Linux
Python version: 3.8.0

I'm not sure if this doesn't work for any other built-ins, so far these are the only functions that don't work.

**Comment by sebastinas** [comment]
I cannot reproduce the issue with Python 3.8.1.
