### ISSUE TITLE
Replace the imp module with importlib

### ISSUE THREAD

**Issue by opensource-assist** [bpython/bpython#791]
The [imp module](https://docs.python.org/dev/library/imp.html) is deprecated and will be removed in a future release. It should be replaced with the importlib module.
The only affected file in bpython is [importcompletion.py](https://github.com/bpython/bpython/blob/master/bpython/importcompletion.py)

Here's the warning when run on my system:
```
/usr/local/lib/python3.9/site-packages/bpython/importcompletion.py:31: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```

**Comment by sebastinas** [comment]
Fix available in #792.
