### ISSUE TITLE
How can I disable the "on top of message"?

### ISSUE THREAD

**Issue by mrillusi0n** [bpython/bpython#793]
```bpython version 0.18 on top of Python3.8.0 /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8```

I'd like to change the way this is displayed. I did not see a way to do it via the `config` file.

**Comment by sebastinas** [comment]
That's not possible currently.

**Comment by sebastinas** [comment]
Actually, it is. Start `bpython` with `-q`.
