### ISSUE TITLE
Your one video is in Python 2

### ISSUE THREAD

**Issue by scopatz** [bpython/bpython#794]
As seen at the top of https://bpython-interpreter.org/screenshots.html, you might want to update this video or remove the link :wink:

**Comment by bk211** [comment]
Hello scopatz,
I'm newbie here and trying to get involved into an open source project for my school project,
So if I have understood, I have to film new video/gif with new version of bpython and update the website right? 
looks pretty friendly for newbie to start, so I'm taking this assignment if you agreed ^^

**Comment by scopatz** [comment]
Hi there @bk211! I am not involved with the project at all, but was just pointing out that the video is rather old.  The link on the site should probably be removed. I don't know if the project wants a new video :wink:

**Comment by ikanobori** [comment]
Hey @scopatz and @bk211 I'm open to having a new video and if @bk211 wants to make one I encourage it! If you have any questions let me know.

Your eventual video could be submitted as a pull request to https://github.com/bpython/bsite which is our repository that contains the website.

**Comment by thomasballinger** [comment]
Looks like this is resolved, thanks @bk211 for fixing and @scopatz for pointing this out!
