### ISSUE TITLE
Publish bpython to Brew

### ISSUE THREAD

**Issue by sumanthratna** [bpython/bpython#799]
I personally prefer to avoid installing packages globally via `pip`, but I'd like to have `bpython` installed globally. I think it'd help a lot of people if `brew install bpython` was possible.

**Comment by sebastinas** [comment]
Shouldn't this be requested at `https://github.com/Homebrew/homebrew-core/issues`?

**Comment by sumanthratna** [comment]
I created this issue here since I believe that the only developers who actually have to do work to close this issue are the bpython developers. I believe Brew already supports Python packages: https://docs.brew.sh/Python-for-Formula-Authors.

**Comment by sebastinas** [comment]
Sure, but formulas are supposed to be submitted there. bpython itself seems to be wrong location for this request.

**Comment by sumanthratna** [comment]
My understanding is that the bpython developers will need to create a PR to https://github.com/Homebrew/homebrew-core in order for bpython to be accepted to brew. Then, the brew maintainers will merge the PR.

**Comment by sebastinas** [comment]
Somebody has to do that, yes. But that can be done by anybody, not only by us.

**Comment by supakeen** [comment]
I'll take a look at publishing to brew.

**Comment by sumanthratna** [comment]
turns out they added this around a week and a half ago: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bpython.rb

`brew install bpython` should work now
