### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by raghavg123** [bpython/bpython#801]
I want to use `bpython` on Windows 10 and it works properly but it gives me the following annoying error on each command passed:
![image](https://user-images.githubusercontent.com/14952412/77739158-10777d80-7037-11ea-9e94-a207d3910cb7.png)

Any workaround for this?

**Comment by sebastinas** [comment]
This should be fixed on the master branch.

**Comment by raghavg123** [comment]
Which file do I have to run then?

**Comment by sebastinas** [comment]
We need to push a new release.
