### ISSUE TITLE
How to disable autocomplete/hints/suggestions?

### ISSUE THREAD

**Issue by bmetcalfe1** [bpython/bpython#805]
What settings do I need to disable autocomplete/hints/suggestions?

For example, when you type 'a' in the shell, I do not want to see "abs(   all(   and    any(   as     ascii( assert async"

Thanks

**Comment by supakeen** [comment]
You can take a look the ``auto_display_list`` settings which should require you to hit tab before you see the completions.

https://docs.bpython-interpreter.org/en/latest/configuration.html#auto-display-list

**Comment by yar00001** [comment]
I have set this setting `auto_display_list = False` but this doesn't seem to work and I am still getting the large box of "suggestion"

**Comment by rhoit** [comment]
same here I haven't been able to close the auto-complete box too.

**Comment by rhoit** [comment]
ahh found the option `autocomplete_mode` in the code, setting it to  'none' fixed the issue as seen in

https://github.com/bpython/bpython/blob/9ce99705b98cc26473db0772b208da05343d0f0a/bpython/autocomplete.py#L60
