### ISSUE TITLE
Dropping Python 2 support

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#819]
As Python 2.7 has now reached its end of life, I think it's time to drop all the special cases to support it. I propose to have 0.20 as last version with Python 2.7 support. @supakeen, @thomasballinger, what do you think?

**Comment by thomasballinger** [comment]
That sounds good to me!

For clarify for others reading (and to confirm) I assume we would not be yanking the old releases or anything, so installing bpython in Python 2 would continue to work; it just wouldn't get any updates.

**Comment by supakeen** [comment]
I'm +1 for dropping support (as I added warnings in 0.19) however I might be wary of dropping it so 'quickly'? 

Do you propose removing all the special cases or to not pay attention to them anymore for 0.21?

@thomasballinger Yea we won't yank old releases :)

**Comment by thomasballinger** [comment]
It doesn't feel too quick to me, if there were a show-stopping bug we could do a point release. (thanks for adding those warnings too!)

**Comment by supakeen** [comment]
Then I agree on the timeframe; @sebastinas did you want to remove all the `if py3` stuff and make it the default or not pay attention to them moving forwards?

**Comment by sebastinas** [comment]
I actually want to remove all the `if py3` code in 0.21. Leaving them in the code base would give the false impression that we still care about Python 2 after we dropped support for it.

Considering how often we prepare releases, 0.21 would only happen sometime sometime in 2021. This will give people some time to move on.

**Comment by supakeen** [comment]
Yea that makes sense; probably 0.20 somewhere this year if I get to my assigned bugs then 0.21 somewhere first half of next year. I'd love to remove as much as possible in that release (see also the frontends ticket in #820 ).

**Comment by sebastinas** [comment]
Fixed in 07f4fe34438ed7090baa31f8ac65316dca873153 and plenty of commits before that one.
