### ISSUE TITLE
Using Python3, bpython only autocompletes packages, not modules

### ISSUE THREAD

**Issue by m0rgen** [bpython/bpython#847]
A simple example...

If I create a directory hierarchy like this:

```
./xyzzy
./xyzzy/__init__.py
./xyzzy/plugh
./xyzzy/plugh/__init__.py
./xyzzy/plugh/bar.py
./xyzzy/plugh/foo.py

```
Running bpython using python2.7.16 will successfully autocomplete "foo" and "bar", e.g. "from xyzzy.plugh." will show "foo" and "bar" in the autocomplete box.  However, running bpython using python3.7.3 it will only autocomplete "xyzzy" or "xyzzy.plugh" (which are packages/directories), while "foo" and "bar" are modules/files.

**Comment by sebastinas** [comment]
This might be related to #835. Did you try with a version of bpython that has that fixed applied?
