### ISSUE TITLE
Curtsies frontend repl fails to start with setuptools >= 50 and watchdog installed

### ISSUE THREAD

**Issue by nolsto** [bpython/bpython#848]
When bpython is installed with the [watch] extra (watchdog installed additionally), The repl fails to start.
Uninstalling watchdog or installing setuptools<50 prevents the issue.

Produced with watchdog 0.10.3, bpython 0.19, python 3.8.5, macOS 10.14.6.
```
bpython version 0.19 on top of Python 3.8.5 /venv/bin/python3.8

Traceback (most recent call last):
  File "/venv/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/bpython/curtsies.py", line 220, in main
    exit_value = repl.mainloop(True, paste)
  File "/venv/lib/python3.8/site-packages/bpython/curtsies.py", line 114, in mainloop
    self.initialize_interp()
  File "/venv/lib/python3.8/site-packages/bpython/curtsiesfrontend/repl.py", line 1873, in initialize_interp
    del self.coderunner.interp.locals["_Helper"]
KeyError: '_Helper'
```

This appears to have something to do with the overridden distutils made in [this setuptools change](https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v5000).
Using the `SETUPTOOLS_USE_DISTUTILS=stdlib` escape hatch it provides prevents the problem as well.

**Comment by sebastinas** [comment]
I don't understand why setuptools would cause this. Please try 46270e068f3775456501c837fec54ec547d6f1b5 as workaround.

**Comment by sebastinas** [comment]
Since I haven't heard back from you, I assume that fixed it.
