### ISSUE TITLE
bpython-curses is not working on windows 10: it deletes the current line and returns back at the start of the history

### ISSUE THREAD

**Issue by giuliohome** [bpython/bpython#859]
If you type and **underscore** in the name of a function

```python
def public_` # I want def public_ip():
```

it deletes the current line and returns back at the start of the history.

after I have typed a dot it shows the possible completions but when I digit a **capital P** it deletes the current line and returns back at the start of the history.

```python
http = urllib3.P # I want http = urllib3.PoolManager()
```

**Note**
Actually this is a big problem of `bpython-curses` *also on Linux* (I've tested it on my Fedora 32, last version) and indeed it is deprecated, but the crucial point is that the real `bpython` is running on Linux but not on Windows.

**Comment by bjhend** [comment]
I've observed the same behavior with bpython-curses but not only with underscore and capital P. In addition this happens also with A, E, G, K, N, and Y (all capital). 

Versions:
Python 3.8.3
bcrypt         3.2.0
blessings      1.7
bpython        0.20
certifi        2020.11.8
cffi           1.14.3
chardet        3.0.4
cryptography   3.2.1
curtsies       0.3.4
greenlet       0.4.17
idna           2.10
paramiko       2.7.2
pip            20.2.4
pycparser      2.20
Pygments       2.7.2
PyNaCl         1.4.0
requests       2.24.0
setuptools     41.2.0
six            1.15.0
urllib3        1.25.11
wcwidth        0.2.5
windows-curses 2.2.0

**Comment by giuliohome** [comment]
@bjhend I've upgraded to the latest version of the package and I confirm that this bug has been fixed.
Thanks to the develpers

**Comment by giuliohome** [comment]
There is another issue, I've noticed, sorry if I am writing here, I know I should open a different issue.
Anyway when I activate a venv and I run bpython-curses from the venv it does not see the package installed under the venv and it can't import them. Of course that is not happening with the vanilla python interpreter. Let me know if I have to open another issue. Thanks again for the released fix.

**Comment by giuliohome** [comment]
> 
> 
> I've observed the same behavior with bpython-curses but not only with underscore and capital P. In addition this happens also with A, E, G, K, N, and Y (all capital).

Of course, it is all the letters in "KEY_NPAGE", have you seen the fiix?
```
elif key in ("KEY_NPAGE",)
```
the comma (added as a fix) transforms what is was wrongly a string (a list of chars) into a correct tuple, in this case a one-element tuple  

> 
> Versions:

> bpython 0.20

@bjhend 
Please upgrade to bpython 0.20.1

**Comment by bjhend** [comment]
Upgrading solved it for me as well, thanks.

**Comment by bjhend** [comment]
Yes, I've looked at the fix (tried it manually first) but didn't compare the letters. Sometimes bugs have funny effects.

**Comment by giuliohome** [comment]
No funny effects, only the intended when. the letters show up, as expected.
Please double check

**Comment by giuliohome** [comment]
![immagine](https://user-images.githubusercontent.com/3272563/99548740-40ee9c00-29b9-11eb-8536-06434b743704.png)

**Comment by bjhend** [comment]
Thanks for the hint. As I said, after upgrading to bpython 0.20.1 as well as after applying the fix manually beforehand, it worked or me.
