### ISSUE TITLE
Get config options programmatically

### ISSUE THREAD

**Issue by adder46** [bpython/bpython#864]
I'm trying to implement bpython support for [pyhstr](https://github.com/adder46/pyhstr) properly, however, I'm having issues retrieving, for example, the `hist_file` option in the `[general]` section of the config file.

**Comment by sebastinas** [comment]
I'm not sure what your specific needs are, but the following should already do what you want:
```py
from bpython.config import loadini, Struct, default_config_path

config = Struct()
loadini(config, default_config_path())
config.hist_file
```

**Comment by adder46** [comment]
Ah, cool. Thanks.
