### ISSUE TITLE
A way to tell if the user is running bpython

### ISSUE THREAD

**Issue by adder46** [bpython/bpython#867]
Is there some robust way to tell if a user is running bpython, interactively or not?

**Comment by sebastinas** [comment]
The design goal is to behave as much as the normal Python REPL wrt to code execution as possible (yes, there are some bugs where bpython does not behave exactly the same). So implementing such a feature would be against its design goal. Why do you need that?

**Comment by adder46** [comment]
I want to determine if the user is running an instance of bpython shell in order to load appropriate history in my [app](https://github.com/adder46/pyhstr).

**Comment by sebastinas** [comment]
bpython will always change `help` to its internal version. So `help.__module__.startswith("bpython")` should tell you if its running under bpython.
