### ISSUE TITLE
How to install bpython on Anaconda windows?

### ISSUE THREAD

**Issue by boardtc** [bpython/bpython#885]
Why lockdown the bPython list if you are not moderating, my post has not got published? https://linux.die.net/man/1/bpython lists the creator emails as robertanthonyfarrel@gmail.com but it bounces, the web page shows robertanth...@gmail.com. Why all this cloak and dagger stuff?

Please, I could like some advice, can you open the list and make it public like e.g. https://groups.google.com/a/continuum.io/g/anaconda

I heard about bpython on the real python podcast. I use Anaconda on Windows 10 and want to try it.

I got the install command from https://anaconda.org/conda-forge/bpython but it gives PackagesNotFoundError

Searching https://anaconda.org/search?q=bpython does not locate a windows package in the anaconda repos

Any advice on how to install the windows version with anaconda?

**Comment by sebastinas** [comment]
See #850.

**Comment by eabase** [comment]
> Why all this cloak and dagger stuff?

Because they still live in the 1990's. Using obscure emailing lists and abandoned google groups &  email accounts, to prevent any sane development, mostly due to personal paranoia?

**Comment by supakeen** [comment]
As you can see by commenting here, we use GitHub for our issues, feature requests, development, and communication. The mailing list is an alternative route for those that prefer it, see: https://bpython-interpreter.org/community.html

Though it is valid that Bob isn't active anymore so I should update the website to reflect that.
