### ISSUE TITLE
Intellisense in VSCode doesn't work while using bypython as interpreter.

### ISSUE THREAD

**Issue by JakronIT** [bpython/bpython#893]
I say right away that I am not an advanced user, but I think something is wrong.

I am using WSL and VSCode combination on my Windows. I installed bpython and everything works fine in the console. Moving on, I chose bpython as the default interpreter in VSCode so that I could run code in the console from VSCode, and use the debugging options. Unfortunately, after this change, the Intelisense prompts stopped working. I went back to pure python and everything works.

Any chance to use bpython in vscode?

**Comment by Jaakkonen** [comment]
Sounds like a error within the VS Code extensions. Are you using Pyright or the Microsoft Python extension? If you're using the Microsoft one which language server do you have (Jedi, microsoft, Pylance?)? Can you get the "Python" extension logs from the VS Code output panel (can be opened when you open the terminal view from the drop down menu that appears there)

**Comment by sebastinas** [comment]
Indeed, that seems unrelated to bpython.
