### ISSUE TITLE
AssertionError: (-1, 163, 5, 0, 0)

### ISSUE THREAD

**Issue by ThatXliner** [bpython/bpython#896]
I just installed bpython using pipx and...
```py
bpython version 0.21 on top of Python 3.7.9 /Users/bryanhu/.local/pipx/venvs/bpython/bin/python

Traceback (most recent call last):
  File "/Users/bryanhu/.local/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/Users/bryanhu/.local/pipx/venvs/bpython/lib/python3.7/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/Users/bryanhu/.local/pipx/venvs/bpython/lib/python3.7/site-packages/bpython/curtsies.py", line 113, in mainloop
    self.process_event_and_paint(None)
  File "/Users/bryanhu/.local/pipx/venvs/bpython/lib/python3.7/site-packages/bpython/curtsies.py", line 95, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/Users/bryanhu/.local/pipx/venvs/bpython/lib/python3.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1615, in paint
    self.cursor_offset,
AssertionError: (-1, 163, 5, 0, 0)
```

**Comment by ThatXliner** [comment]
Repro percentage: 100% (even after restarting my terminal)
(Possible) Repro steps:
 - Install bpython using pipx
 - Run bpython-curses several times
 - Run bpython

Possibly useful:
<img width="762" alt="Screen Shot 2021-05-08 at 5 50 26 PM" src="https://user-images.githubusercontent.com/66848002/117557252-e0662080-b025-11eb-887e-402882d19b57.png">

**Comment by sebastinas** [comment]
Are you using cwcwidth version 0.1.3 or newer?

**Comment by ThatXliner** [comment]
> Are you using cwcwidth version 0.1.3 or newer?


How do I test that?

**Comment by ThatXliner** [comment]
<img width="762" alt="Screen Shot 2021-05-10 at 9 14 39 AM" src="https://user-images.githubusercontent.com/66848002/117690863-26c79680-b170-11eb-9110-8b5b6ce097b6.png">

**Comment by sebastinas** [comment]
Okay, this looks like a case where `cwcwidth` fails to determine the length of a string with your locale. So: what's your locale? On the `main` branch you can also run `bpython -l info -L log` and check the file `log` for the version and environment variable output.

**Comment by ThatXliner** [comment]
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```
<img width="762" alt="Screen Shot 2021-05-12 at 2 30 27 PM" src="https://user-images.githubusercontent.com/66848002/118046753-9edbbb00-b32e-11eb-943f-6aa5feabfa01.png">

**Comment by sebastinas** [comment]
Thanks. `\r` shouldn't be contained in that string. I'll need to find out if some code path acts differently under iTerm2 that causes `\r` to be present. I suppose you are using the default config, right?

**Comment by ThatXliner** [comment]
> I suppose you are using the default config, right?

No, I did [quite ￼some customizations￼](https://github.com/ThatXliner/setup#iterm2)

**Comment by sebastinas** [comment]
I meant your bpython config. Did you change it's ps1 or ps2?

**Comment by sebastinas** [comment]
Okay, I think I got it. Your `sys.ps1` i set to `\r>>> `. I guess we need to strip `\r` in that case.

**Comment by ThatXliner** [comment]
Yes, my `sys.ps1` is configured. To be precise, it has ansi escapes in them. I added the `/r` just in case (pasting was getting wonky but now I figured it's Python's fault. I can change it back if I need to make this work)

**Comment by sebastinas** [comment]
At least the `\r` is a problem. In any case, I'll fix it to not fail but ignore it in case `bpython` cannot handle it.
