### ISSUE TITLE
Autoclose brackets,qoutes,[,{

### ISSUE THREAD

**Issue by yogeshdcool** [bpython/bpython#905]
Is it possible to complete the brackets and other symbols mentioned in the title and It would be cool to have the cursor placed between them after completing the pair.

**Comment by samuelgregorovic** [comment]
i could work on this, if you would assign it to me :)

**Comment by thomasballinger** [comment]
Great, this will interact with completion in cases like `foo(a|)` and `bar[a|]` which you're familiar with.

I think this feature will need to be turned on by users with a config option, unless it can be made to work with existing users' muscle memory: things like pressing `)` from `foo(abc|)` would overwrite the closing paren, just moving the cursor to `foo(abc)`? I think some text editors do that.

**Comment by thomasballinger** [comment]
I don't think we should make it the default behavior unless it works well for people who aren't used to the behavior, so before this gets in we'd need to add a config option. That part will be easy though, I wouldn't worry about it for now.

**Comment by samuelgregorovic** [comment]
@thomasballinger i am finishing this feature up. Do you wish to control whether the completion should work via command line argument or via a config file?

**Comment by thomasballinger** [comment]
That's great, feel free to make an unfinished PR for feedback. I think this should have a config file way to toggle it (press F3 in bpython to view/create a config file). See config.py for this code.

**Comment by samuelgregorovic** [comment]
@thomasballinger will do :) thanks

**Comment by sebastinas** [comment]
Implemented in #934.
