### ISSUE TITLE
Ctrl+C mapped to QWERTY placement regardless of layout

### ISSUE THREAD

**Issue by Jaakkonen** [bpython/bpython#908]
Pressing `Ctrl+C` on Workman keyboard layout does nothing but instead `Ctrl+M` does the function of `Ctrl+C` (QWERTY key C is M on Workman).

By convention CLI programs do not bind to layout specific scan codes but instead bind to the key combinations that take keyboard layout to count.

The same issue seems to be affecting IPython so the issue is probably in the prompt toolkit

**Comment by sebastinas** [comment]
Does `python3 - m curtsies.input` and then Ctrl-c exit with a `KeyboardInterrupt`?

**Comment by Jaakkonen** [comment]
> Does python3 -m curtsies.input and then Ctrl-c exit with a KeyboardInterrupt?
Yes.

Trying to reproduce this issue now it seems that I get keyboard interrupts with `<Ctrl+C>` keycombo regardless of keyboard layout but holding other keybinding (for example `<Ctrl+M>`) for a while and then pressing `<Ctrl+C>` will cause the `<Ctrl+C>` to be handled only after typing a character. 

So it seems I misidentified the issue by first keeping some combination like `<Ctrl+M>` pressed, then pressing `<Ctrl+C>` (which gets "queued") and then hitting the QWERTY C key `<Ctrl+M>` which releases the actual `<Ctrl+C>` from "queue" and causes `KeyboardInterrupt`.

Thus the problem is not a problem with keyboard layout but instead with this "queuing" behavior.

**Comment by NicoAdrian** [comment]
@Jaakkonen Can confirm this behaviour on WSL2 (ubuntu 18.04) with the latest release of bpython. When I want to cancel what I'm typing, pressing `<Ctrl+C>` doesn't immediatly raise KeyboardInterrupt, I am forced to press any key for it to happen.

**Comment by sebastinas** [comment]
@Jaakkonen, @NicoAdrian please test again with the new curtsies version and let us know if that fixed this issue as well.

**Comment by NicoAdrian** [comment]
@sebastinas it does, thanks.
