### ISSUE TITLE
Crash when print ANSI escape code to color output text

### ISSUE THREAD

**Issue by arian-deimling** [bpython/bpython#915]
Tried printing out an ANSI escape sequence that changes the color of terminal output to red (see: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), and it crashed. If I don't pass the `end=''` parameter to the `print` function, it works fine; looks like `bpython` was expecting the cursor to advance but only changing the color doesn't do that.

```
~ % bpython
bpython version 0.21 on top of Python 3.8.2 /Library/Developer/CommandLineTools/usr/bin/python3
>>> print('\033[91m', end='')

Traceback (most recent call last):
  File "/Users/arian/Library/Python/3.8/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsies.py", line 121, in mainloop
    self.process_event_and_paint(e)
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsies.py", line 95, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsiesfrontend/repl.py", line 1610, in paint
    assert cursor_row >= 0 and cursor_column >= 0, (
AssertionError: (-1, 74, 9, 0, 0)
```

**Comment by arian-deimling** [comment]
Can I work on this or are you?

**Comment by arian-deimling** [comment]
Duplicate of #900.

**Comment by thomasballinger** [comment]
@arian-deimling late to reply, but you're welcome to look. I suspect https://github.com/bpython/curtsies/blob/main/curtsies/escseqparse.py may be useful to look at, and that we may need to special case printing what we're going to treat as printing nothing.

**Comment by thomasballinger** [comment]
This bug might even be the most pressing bug right now? It looks pretty involved though, decisions made here about how we handle operationally blank output lines may have far-reaching effects.

I'm starting on some mypy types, that's a potential thing to work on if that's fun. In the autocompletion vein, you could take a look at https://github.com/bpython/bpython/issues/889 or https://github.com/bpython/bpython/issues/897 or similar. I'm interested in https://github.com/bpython/bpython/issues/826, which is related to the escape codes issue.
