### ISSUE TITLE
Autocomplete font black on black in kitty

### ISSUE THREAD

**Issue by ecarl65** [bpython/bpython#950]
I use the kitty terminal and it's been great. The only problem I've had is with bpython. When it is autocompleting something, like say `import numpy as np`, it is putting the autocomplete font as black on the already black background. In other terminals, like konsole or gnome-terminal, with black backgrounds it doesn't do that, it knows to make the font grey. I've tried creating all manner of custom themes but none of the settings seem to impact this. Any times on how I can change this behavior?

**Comment by thomasballinger** [comment]
I believe you're describing "right_arrow_suggestion" in the color theme (or do you mean the method/attribute completion box?), see https://docs.bpython-interpreter.org/en/latest/themes.html#themes for how to change this color scheme.

**Comment by ecarl65** [comment]
Thanks! I could have sworn I tried changing that but I just went in and did it on a theme of my creation and it seems to work!
