### ISSUE TITLE
Bpython fails to open new window with Tkinter

### ISSUE THREAD

**Issue by thevibingcat** [bpython/bpython#956]
I attempted to use the Module Tkinter, but when i tried to open a new window (named tk), nothing happened,
`>>> from tkinter import *
>>> tk = Tk()
>>> btn = Button(tk, text="click me")
>>> btn.pack()
>>> tk = Tk()
>>> btn = Button(tk, text="Click me", command=hello)
>>> btn.pack()
>>> tk = Tk()
>>> canvas = Canvas(tk, width=500, height=500)
>>> canvas.pack
<bound method Pack.pack_configure of <tkinter.Canvas object .!canvas>>
>>> canvas.pack()`
the problem occurs on the second line of code (tk = Tk()), where bpython i supposed to open a window named tk, but nothing happens.
bpython v0.18, IDLE v3.8.10

**Comment by sebastinas** [comment]
Workaround: execute `tk.mainloop()`.

**Comment by thevibingcat** [comment]
Thank you
