### ISSUE TITLE
Docstrings confuse autocompletion

### ISSUE THREAD

**Issue by Andriamanitra** [bpython/bpython#966]
I ran into an issue where the autocompletion starts thinking an example from the docstring of the function is the signature of the function.

The original code where I ran into this was a bit more complicated but I managed to create a somewhat minimal reproduction (the inheritance is significant, without inheriting it works correctly):
```python
from collections.abc import Sequence


class C(Sequence):
    @classmethod
    def cmethod(cls, number: int, lst: list[int] = []):
        """
        Return a list of numbers

        Example:
        ========
        C.cmethod(1337, [1, 2]) # => [1, 2, 1337]
        """
        return lst + [number]

```

![image](https://user-images.githubusercontent.com/10672443/186619086-e1655cdc-e882-491b-a232-f6cf403c9cae.png)

The autocompletion (and the documentation pop-up) seems to not realize that 1337 and [1 and 2 are literals rather than parameter names, and the `cls` parameter for a class method gets turned into `obj` for whatever reason.

**Comment by sebastinas** [comment]
There are multiple issues as far as I can tell. First issue is that parsing of default values is broken in with type annotations.

**Comment by sebastinas** [comment]
Indeed, `fixlongargs` is broken with type annotations.
