### ISSUE TITLE
Can not import `dateutil` with bpython

### ISSUE THREAD

**Issue by kjozsa** [bpython/bpython#977]
Using a virtualenv:

```
/tmp/bp-issue 🐍 $ pip list
Package         Version
--------------- -------
pip             22.3.1
python-dateutil 2.8.2
setuptools      65.6.3
six             1.16.0
wheel           0.38.4

/tmp/bp-issue 🐍 $ bpython
bpython version 0.23 on top of Python 3.10.9 /usr/bin/python
>>> import dateutil
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import dateutil
ModuleNotFoundError: No module named 'dateutil'
>>> 

/tmp/bp-issue 🐍 $ python
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateutil
>>> 
```

Am I doing something wrong or that's an issue with bpython?

edit: format, readability

**Comment by sebastinas** [comment]
From the package list, it looks like you are mixing two environments. If you want to use bpython inside a virtualenv, you also need to install it there.

**Comment by kjozsa** [comment]
Hmn so I can not use it as an interpreter invoked from my outer environment? That makes sense.. thanks much for your quick help!

**Comment by sebastinas** [comment]
Depending on how you installed bpython in the outer environment, launching bpython will ensure that it is running in the outside environment. You might be able to mess around with PYTHONPATH, but then you get to keep the pieces.
